#!/usr/bin/env bash
# PreToolUse hook: block edits to lock files and generated code
set -euo pipefail

INPUT=$(cat)
FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

[ -z "$FILE" ] && exit 0

BASENAME=$(basename "$FILE")

case "$BASENAME" in
  pnpm-lock.yaml|package-lock.json|yarn.lock|go.sum)
    echo '{"decision":"block","reason":"Lock files should not be edited manually. Run the package manager instead."}'
    exit 0
    ;;
esac

# Block sqlc generated code
if [[ "$FILE" == */backend/internal/store/*.sql.go ]] || [[ "$FILE" == */internal/store/*.sql.go ]]; then
  echo '{"decision":"block","reason":"This file is generated by sqlc. Edit queries/*.sql and run make sqlc instead."}'
  exit 0
fi

exit 0
