version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - copyloopvar

  settings:
    govet:
      enable:
        - copylocks
        - loopclosure
        - lostcancel
        - atomic

  exclusions:
    paths:
      - backend
      - ".*\\.sql\\.go$"

run:
  timeout: 3m
  tests: true
  build-tags:
    - spike

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
