services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - NODE_ENV=development

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: ["air", "-c", ".air.toml"]
    volumes:
      - ./backend:/app
    environment:
      - GO_ENV=development

  ws:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: ["air", "-c", ".air.toml", "--", "ws"]
    volumes:
      - ./backend:/app
    environment:
      - GO_ENV=development

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: ["air", "-c", ".air.toml", "--", "worker"]
    volumes:
      - ./backend:/app
    environment:
      - GO_ENV=development
