FROM golang:1.25-alpine

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod ./
# go.sum may not exist yet; glob pattern copies it only if present
COPY go.su[m] ./
RUN go mod download

COPY . .

EXPOSE 8080 8081

CMD ["air", "-c", ".air.toml"]
