// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: demos.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countDemosByUserID = `-- name: CountDemosByUserID :one
SELECT count(*) FROM demos WHERE user_id = $1
`

func (q *Queries) CountDemosByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDemosByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDemo = `-- name: CreateDemo :one
INSERT INTO demos (user_id, faceit_match_id, map_name, file_path, file_size, status, match_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, faceit_match_id, map_name, file_path, file_size, status, total_ticks, tick_rate, duration_secs, match_date, created_at
`

type CreateDemoParams struct {
	UserID        uuid.UUID
	FaceitMatchID sql.NullString
	MapName       string
	FilePath      string
	FileSize      int64
	Status        string
	MatchDate     sql.NullTime
}

func (q *Queries) CreateDemo(ctx context.Context, arg CreateDemoParams) (Demo, error) {
	row := q.db.QueryRowContext(ctx, createDemo,
		arg.UserID,
		arg.FaceitMatchID,
		arg.MapName,
		arg.FilePath,
		arg.FileSize,
		arg.Status,
		arg.MatchDate,
	)
	var i Demo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FaceitMatchID,
		&i.MapName,
		&i.FilePath,
		&i.FileSize,
		&i.Status,
		&i.TotalTicks,
		&i.TickRate,
		&i.DurationSecs,
		&i.MatchDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDemo = `-- name: DeleteDemo :exec
DELETE FROM demos WHERE id = $1
`

func (q *Queries) DeleteDemo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDemo, id)
	return err
}

const getDemoByID = `-- name: GetDemoByID :one
SELECT id, user_id, faceit_match_id, map_name, file_path, file_size, status, total_ticks, tick_rate, duration_secs, match_date, created_at FROM demos WHERE id = $1
`

func (q *Queries) GetDemoByID(ctx context.Context, id uuid.UUID) (Demo, error) {
	row := q.db.QueryRowContext(ctx, getDemoByID, id)
	var i Demo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FaceitMatchID,
		&i.MapName,
		&i.FilePath,
		&i.FileSize,
		&i.Status,
		&i.TotalTicks,
		&i.TickRate,
		&i.DurationSecs,
		&i.MatchDate,
		&i.CreatedAt,
	)
	return i, err
}

const listDemosByUserID = `-- name: ListDemosByUserID :many
SELECT id, user_id, faceit_match_id, map_name, file_path, file_size, status, total_ticks, tick_rate, duration_secs, match_date, created_at FROM demos
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDemosByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListDemosByUserID(ctx context.Context, arg ListDemosByUserIDParams) ([]Demo, error) {
	rows, err := q.db.QueryContext(ctx, listDemosByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Demo
	for rows.Next() {
		var i Demo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FaceitMatchID,
			&i.MapName,
			&i.FilePath,
			&i.FileSize,
			&i.Status,
			&i.TotalTicks,
			&i.TickRate,
			&i.DurationSecs,
			&i.MatchDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDemoAfterParse = `-- name: UpdateDemoAfterParse :one
UPDATE demos SET
    status = 'ready',
    total_ticks = $2,
    tick_rate = $3,
    duration_secs = $4
WHERE id = $1
RETURNING id, user_id, faceit_match_id, map_name, file_path, file_size, status, total_ticks, tick_rate, duration_secs, match_date, created_at
`

type UpdateDemoAfterParseParams struct {
	ID           uuid.UUID
	TotalTicks   sql.NullInt32
	TickRate     sql.NullFloat64
	DurationSecs sql.NullInt32
}

func (q *Queries) UpdateDemoAfterParse(ctx context.Context, arg UpdateDemoAfterParseParams) (Demo, error) {
	row := q.db.QueryRowContext(ctx, updateDemoAfterParse,
		arg.ID,
		arg.TotalTicks,
		arg.TickRate,
		arg.DurationSecs,
	)
	var i Demo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FaceitMatchID,
		&i.MapName,
		&i.FilePath,
		&i.FileSize,
		&i.Status,
		&i.TotalTicks,
		&i.TickRate,
		&i.DurationSecs,
		&i.MatchDate,
		&i.CreatedAt,
	)
	return i, err
}

const updateDemoStatus = `-- name: UpdateDemoStatus :one
UPDATE demos SET status = $2 WHERE id = $1
RETURNING id, user_id, faceit_match_id, map_name, file_path, file_size, status, total_ticks, tick_rate, duration_secs, match_date, created_at
`

type UpdateDemoStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateDemoStatus(ctx context.Context, arg UpdateDemoStatusParams) (Demo, error) {
	row := q.db.QueryRowContext(ctx, updateDemoStatus, arg.ID, arg.Status)
	var i Demo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FaceitMatchID,
		&i.MapName,
		&i.FilePath,
		&i.FileSize,
		&i.Status,
		&i.TotalTicks,
		&i.TickRate,
		&i.DurationSecs,
		&i.MatchDate,
		&i.CreatedAt,
	)
	return i, err
}
