// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: faceit_matches.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFaceitMatch = `-- name: CreateFaceitMatch :one
INSERT INTO faceit_matches (user_id, faceit_match_id, map_name, score_team, score_opponent, result, elo_before, elo_after, kills, deaths, assists, demo_url, demo_id, played_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, user_id, faceit_match_id, map_name, score_team, score_opponent, result, elo_before, elo_after, kills, deaths, assists, demo_url, demo_id, played_at, created_at
`

type CreateFaceitMatchParams struct {
	UserID        uuid.UUID
	FaceitMatchID string
	MapName       string
	ScoreTeam     int16
	ScoreOpponent int16
	Result        string
	EloBefore     sql.NullInt32
	EloAfter      sql.NullInt32
	Kills         sql.NullInt16
	Deaths        sql.NullInt16
	Assists       sql.NullInt16
	DemoUrl       sql.NullString
	DemoID        uuid.NullUUID
	PlayedAt      time.Time
}

func (q *Queries) CreateFaceitMatch(ctx context.Context, arg CreateFaceitMatchParams) (FaceitMatch, error) {
	row := q.db.QueryRowContext(ctx, createFaceitMatch,
		arg.UserID,
		arg.FaceitMatchID,
		arg.MapName,
		arg.ScoreTeam,
		arg.ScoreOpponent,
		arg.Result,
		arg.EloBefore,
		arg.EloAfter,
		arg.Kills,
		arg.Deaths,
		arg.Assists,
		arg.DemoUrl,
		arg.DemoID,
		arg.PlayedAt,
	)
	var i FaceitMatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FaceitMatchID,
		&i.MapName,
		&i.ScoreTeam,
		&i.ScoreOpponent,
		&i.Result,
		&i.EloBefore,
		&i.EloAfter,
		&i.Kills,
		&i.Deaths,
		&i.Assists,
		&i.DemoUrl,
		&i.DemoID,
		&i.PlayedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFaceitMatchesByUserID = `-- name: DeleteFaceitMatchesByUserID :exec
DELETE FROM faceit_matches WHERE user_id = $1
`

func (q *Queries) DeleteFaceitMatchesByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFaceitMatchesByUserID, userID)
	return err
}

const getEloHistory = `-- name: GetEloHistory :many
SELECT id, faceit_match_id, map_name, elo_after, played_at
FROM faceit_matches
WHERE user_id = $1 AND played_at >= $2
ORDER BY played_at ASC
`

type GetEloHistoryParams struct {
	UserID   uuid.UUID
	PlayedAt time.Time
}

type GetEloHistoryRow struct {
	ID            uuid.UUID
	FaceitMatchID string
	MapName       string
	EloAfter      sql.NullInt32
	PlayedAt      time.Time
}

func (q *Queries) GetEloHistory(ctx context.Context, arg GetEloHistoryParams) ([]GetEloHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getEloHistory, arg.UserID, arg.PlayedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEloHistoryRow
	for rows.Next() {
		var i GetEloHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.FaceitMatchID,
			&i.MapName,
			&i.EloAfter,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFaceitMatchByID = `-- name: GetFaceitMatchByID :one
SELECT id, user_id, faceit_match_id, map_name, score_team, score_opponent, result, elo_before, elo_after, kills, deaths, assists, demo_url, demo_id, played_at, created_at FROM faceit_matches WHERE id = $1
`

func (q *Queries) GetFaceitMatchByID(ctx context.Context, id uuid.UUID) (FaceitMatch, error) {
	row := q.db.QueryRowContext(ctx, getFaceitMatchByID, id)
	var i FaceitMatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FaceitMatchID,
		&i.MapName,
		&i.ScoreTeam,
		&i.ScoreOpponent,
		&i.Result,
		&i.EloBefore,
		&i.EloAfter,
		&i.Kills,
		&i.Deaths,
		&i.Assists,
		&i.DemoUrl,
		&i.DemoID,
		&i.PlayedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFaceitMatchesByUserID = `-- name: GetFaceitMatchesByUserID :many
SELECT id, user_id, faceit_match_id, map_name, score_team, score_opponent, result, elo_before, elo_after, kills, deaths, assists, demo_url, demo_id, played_at, created_at FROM faceit_matches
WHERE user_id = $1
ORDER BY played_at DESC
LIMIT $2 OFFSET $3
`

type GetFaceitMatchesByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetFaceitMatchesByUserID(ctx context.Context, arg GetFaceitMatchesByUserIDParams) ([]FaceitMatch, error) {
	rows, err := q.db.QueryContext(ctx, getFaceitMatchesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FaceitMatch
	for rows.Next() {
		var i FaceitMatch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FaceitMatchID,
			&i.MapName,
			&i.ScoreTeam,
			&i.ScoreOpponent,
			&i.Result,
			&i.EloBefore,
			&i.EloAfter,
			&i.Kills,
			&i.Deaths,
			&i.Assists,
			&i.DemoUrl,
			&i.DemoID,
			&i.PlayedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkFaceitMatchToDemo = `-- name: LinkFaceitMatchToDemo :one
UPDATE faceit_matches SET demo_id = $2 WHERE id = $1
RETURNING id, user_id, faceit_match_id, map_name, score_team, score_opponent, result, elo_before, elo_after, kills, deaths, assists, demo_url, demo_id, played_at, created_at
`

type LinkFaceitMatchToDemoParams struct {
	ID     uuid.UUID
	DemoID uuid.NullUUID
}

func (q *Queries) LinkFaceitMatchToDemo(ctx context.Context, arg LinkFaceitMatchToDemoParams) (FaceitMatch, error) {
	row := q.db.QueryRowContext(ctx, linkFaceitMatchToDemo, arg.ID, arg.DemoID)
	var i FaceitMatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FaceitMatchID,
		&i.MapName,
		&i.ScoreTeam,
		&i.ScoreOpponent,
		&i.Result,
		&i.EloBefore,
		&i.EloAfter,
		&i.Kills,
		&i.Deaths,
		&i.Assists,
		&i.DemoUrl,
		&i.DemoID,
		&i.PlayedAt,
		&i.CreatedAt,
	)
	return i, err
}
