// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: grenade_lineups.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createGrenadeLineup = `-- name: CreateGrenadeLineup :one
INSERT INTO grenade_lineups (user_id, demo_id, tick, map_name, grenade_type, throw_x, throw_y, throw_z, throw_yaw, throw_pitch, land_x, land_y, land_z, title, description, tags, is_favorite)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, user_id, demo_id, tick, map_name, grenade_type, throw_x, throw_y, throw_z, throw_yaw, throw_pitch, land_x, land_y, land_z, title, description, tags, is_favorite, created_at
`

type CreateGrenadeLineupParams struct {
	UserID      uuid.UUID
	DemoID      uuid.NullUUID
	Tick        sql.NullInt32
	MapName     string
	GrenadeType string
	ThrowX      float32
	ThrowY      float32
	ThrowZ      float32
	ThrowYaw    float32
	ThrowPitch  float32
	LandX       float32
	LandY       float32
	LandZ       float32
	Title       string
	Description sql.NullString
	Tags        []string
	IsFavorite  bool
}

func (q *Queries) CreateGrenadeLineup(ctx context.Context, arg CreateGrenadeLineupParams) (GrenadeLineup, error) {
	row := q.db.QueryRowContext(ctx, createGrenadeLineup,
		arg.UserID,
		arg.DemoID,
		arg.Tick,
		arg.MapName,
		arg.GrenadeType,
		arg.ThrowX,
		arg.ThrowY,
		arg.ThrowZ,
		arg.ThrowYaw,
		arg.ThrowPitch,
		arg.LandX,
		arg.LandY,
		arg.LandZ,
		arg.Title,
		arg.Description,
		pq.Array(arg.Tags),
		arg.IsFavorite,
	)
	var i GrenadeLineup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DemoID,
		&i.Tick,
		&i.MapName,
		&i.GrenadeType,
		&i.ThrowX,
		&i.ThrowY,
		&i.ThrowZ,
		&i.ThrowYaw,
		&i.ThrowPitch,
		&i.LandX,
		&i.LandY,
		&i.LandZ,
		&i.Title,
		&i.Description,
		pq.Array(&i.Tags),
		&i.IsFavorite,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGrenadeLineup = `-- name: DeleteGrenadeLineup :exec
DELETE FROM grenade_lineups WHERE id = $1
`

func (q *Queries) DeleteGrenadeLineup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGrenadeLineup, id)
	return err
}

const getGrenadeLineupByID = `-- name: GetGrenadeLineupByID :one
SELECT id, user_id, demo_id, tick, map_name, grenade_type, throw_x, throw_y, throw_z, throw_yaw, throw_pitch, land_x, land_y, land_z, title, description, tags, is_favorite, created_at FROM grenade_lineups WHERE id = $1
`

func (q *Queries) GetGrenadeLineupByID(ctx context.Context, id uuid.UUID) (GrenadeLineup, error) {
	row := q.db.QueryRowContext(ctx, getGrenadeLineupByID, id)
	var i GrenadeLineup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DemoID,
		&i.Tick,
		&i.MapName,
		&i.GrenadeType,
		&i.ThrowX,
		&i.ThrowY,
		&i.ThrowZ,
		&i.ThrowYaw,
		&i.ThrowPitch,
		&i.LandX,
		&i.LandY,
		&i.LandZ,
		&i.Title,
		&i.Description,
		pq.Array(&i.Tags),
		&i.IsFavorite,
		&i.CreatedAt,
	)
	return i, err
}

const listGrenadeLineupsByMapAndType = `-- name: ListGrenadeLineupsByMapAndType :many
SELECT id, user_id, demo_id, tick, map_name, grenade_type, throw_x, throw_y, throw_z, throw_yaw, throw_pitch, land_x, land_y, land_z, title, description, tags, is_favorite, created_at FROM grenade_lineups
WHERE user_id = $1 AND map_name = $2 AND grenade_type = $3
ORDER BY created_at DESC
`

type ListGrenadeLineupsByMapAndTypeParams struct {
	UserID      uuid.UUID
	MapName     string
	GrenadeType string
}

func (q *Queries) ListGrenadeLineupsByMapAndType(ctx context.Context, arg ListGrenadeLineupsByMapAndTypeParams) ([]GrenadeLineup, error) {
	rows, err := q.db.QueryContext(ctx, listGrenadeLineupsByMapAndType, arg.UserID, arg.MapName, arg.GrenadeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrenadeLineup
	for rows.Next() {
		var i GrenadeLineup
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DemoID,
			&i.Tick,
			&i.MapName,
			&i.GrenadeType,
			&i.ThrowX,
			&i.ThrowY,
			&i.ThrowZ,
			&i.ThrowYaw,
			&i.ThrowPitch,
			&i.LandX,
			&i.LandY,
			&i.LandZ,
			&i.Title,
			&i.Description,
			pq.Array(&i.Tags),
			&i.IsFavorite,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrenadeLineupsByUserID = `-- name: ListGrenadeLineupsByUserID :many
SELECT id, user_id, demo_id, tick, map_name, grenade_type, throw_x, throw_y, throw_z, throw_yaw, throw_pitch, land_x, land_y, land_z, title, description, tags, is_favorite, created_at FROM grenade_lineups
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListGrenadeLineupsByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListGrenadeLineupsByUserID(ctx context.Context, arg ListGrenadeLineupsByUserIDParams) ([]GrenadeLineup, error) {
	rows, err := q.db.QueryContext(ctx, listGrenadeLineupsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrenadeLineup
	for rows.Next() {
		var i GrenadeLineup
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DemoID,
			&i.Tick,
			&i.MapName,
			&i.GrenadeType,
			&i.ThrowX,
			&i.ThrowY,
			&i.ThrowZ,
			&i.ThrowYaw,
			&i.ThrowPitch,
			&i.LandX,
			&i.LandY,
			&i.LandZ,
			&i.Title,
			&i.Description,
			pq.Array(&i.Tags),
			&i.IsFavorite,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleLineupFavorite = `-- name: ToggleLineupFavorite :one
UPDATE grenade_lineups SET is_favorite = NOT is_favorite WHERE id = $1
RETURNING id, user_id, demo_id, tick, map_name, grenade_type, throw_x, throw_y, throw_z, throw_yaw, throw_pitch, land_x, land_y, land_z, title, description, tags, is_favorite, created_at
`

func (q *Queries) ToggleLineupFavorite(ctx context.Context, id uuid.UUID) (GrenadeLineup, error) {
	row := q.db.QueryRowContext(ctx, toggleLineupFavorite, id)
	var i GrenadeLineup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DemoID,
		&i.Tick,
		&i.MapName,
		&i.GrenadeType,
		&i.ThrowX,
		&i.ThrowY,
		&i.ThrowZ,
		&i.ThrowYaw,
		&i.ThrowPitch,
		&i.LandX,
		&i.LandY,
		&i.LandZ,
		&i.Title,
		&i.Description,
		pq.Array(&i.Tags),
		&i.IsFavorite,
		&i.CreatedAt,
	)
	return i, err
}
