// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: heatmaps.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getDemosByIDs = `-- name: GetDemosByIDs :many
SELECT id, user_id, map_name FROM demos
WHERE id = ANY($1::uuid[])
`

type GetDemosByIDsRow struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	MapName sql.NullString
}

func (q *Queries) GetDemosByIDs(ctx context.Context, demoIds []uuid.UUID) ([]GetDemosByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDemosByIDs, pq.Array(demoIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDemosByIDsRow
	for rows.Next() {
		var i GetDemosByIDsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.MapName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHeatmapAggregation = `-- name: GetHeatmapAggregation :many
SELECT ge.x, ge.y, count(*)::bigint AS kill_count
FROM game_events ge
LEFT JOIN player_rounds pr
    ON pr.round_id = ge.round_id AND pr.steam_id = ge.attacker_steam_id
WHERE ge.demo_id = ANY($1::uuid[])
  AND ge.event_type = 'kill'
  AND ge.x IS NOT NULL
  AND ge.y IS NOT NULL
  AND ($2::text IS NULL OR ge.attacker_steam_id = $2)
  AND ($3::text IS NULL OR (pr.team_side IS NOT NULL AND pr.team_side = $3))
  AND (cardinality($4::text[]) = 0 OR ge.weapon = ANY($4::text[]))
GROUP BY ge.x, ge.y
`

type GetHeatmapAggregationParams struct {
	DemoIds       []uuid.UUID
	PlayerSteamID sql.NullString
	Side          sql.NullString
	Weapons       []string
}

type GetHeatmapAggregationRow struct {
	X         sql.NullFloat64
	Y         sql.NullFloat64
	KillCount int64
}

func (q *Queries) GetHeatmapAggregation(ctx context.Context, arg GetHeatmapAggregationParams) ([]GetHeatmapAggregationRow, error) {
	rows, err := q.db.QueryContext(ctx, getHeatmapAggregation,
		pq.Array(arg.DemoIds),
		arg.PlayerSteamID,
		arg.Side,
		pq.Array(arg.Weapons),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHeatmapAggregationRow
	for rows.Next() {
		var i GetHeatmapAggregationRow
		if err := rows.Scan(&i.X, &i.Y, &i.KillCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
