// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Demo struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	FaceitMatchID sql.NullString
	MapName       string
	FilePath      string
	FileSize      int64
	Status        string
	TotalTicks    sql.NullInt32
	TickRate      sql.NullFloat64
	DurationSecs  sql.NullInt32
	MatchDate     sql.NullTime
	CreatedAt     time.Time
}

type FaceitMatch struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	FaceitMatchID string
	MapName       string
	ScoreTeam     int16
	ScoreOpponent int16
	Result        string
	EloBefore     sql.NullInt32
	EloAfter      sql.NullInt32
	Kills         sql.NullInt16
	Deaths        sql.NullInt16
	Assists       sql.NullInt16
	DemoUrl       sql.NullString
	DemoID        uuid.NullUUID
	PlayedAt      time.Time
	CreatedAt     time.Time
}

type GameEvent struct {
	ID              uuid.UUID
	DemoID          uuid.UUID
	RoundID         uuid.NullUUID
	Tick            int32
	EventType       string
	AttackerSteamID sql.NullString
	VictimSteamID   sql.NullString
	Weapon          sql.NullString
	X               sql.NullFloat64
	Y               sql.NullFloat64
	Z               sql.NullFloat64
	ExtraData       pqtype.NullRawMessage
}

type GrenadeLineup struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	DemoID      uuid.NullUUID
	Tick        sql.NullInt32
	MapName     string
	GrenadeType string
	ThrowX      float32
	ThrowY      float32
	ThrowZ      float32
	ThrowYaw    float32
	ThrowPitch  float32
	LandX       float32
	LandY       float32
	LandZ       float32
	Title       string
	Description sql.NullString
	Tags        []string
	IsFavorite  bool
	CreatedAt   time.Time
}

type PlayerRound struct {
	ID            uuid.UUID
	RoundID       uuid.UUID
	SteamID       string
	PlayerName    string
	TeamSide      string
	Kills         int16
	Deaths        int16
	Assists       int16
	Damage        int32
	HeadshotKills int16
	FirstKill     bool
	FirstDeath    bool
	ClutchKills   int16
}

type Round struct {
	ID          uuid.UUID
	DemoID      uuid.UUID
	RoundNumber int16
	StartTick   int32
	EndTick     int32
	WinnerSide  string
	WinReason   string
	CtScore     int16
	TScore      int16
}

type StrategyBoard struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Title      string
	MapName    string
	YjsState   []byte
	ShareMode  string
	ShareToken sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type TickDatum struct {
	Time    time.Time
	DemoID  uuid.UUID
	Tick    int32
	SteamID string
	X       float32
	Y       float32
	Z       float32
	Yaw     float32
	Health  int16
	Armor   int16
	IsAlive bool
	Weapon  sql.NullString
}

type User struct {
	ID          uuid.UUID
	FaceitID    string
	Nickname    string
	AvatarUrl   sql.NullString
	FaceitElo   sql.NullInt32
	FaceitLevel sql.NullInt16
	Country     sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
