// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rounds.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (demo_id, round_number, start_tick, end_tick, winner_side, win_reason, ct_score, t_score, is_overtime)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, demo_id, round_number, start_tick, end_tick, winner_side, win_reason, ct_score, t_score, is_overtime
`

type CreateRoundParams struct {
	DemoID      uuid.UUID
	RoundNumber int16
	StartTick   int32
	EndTick     int32
	WinnerSide  string
	WinReason   string
	CtScore     int16
	TScore      int16
	IsOvertime  bool
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error) {
	row := q.db.QueryRowContext(ctx, createRound,
		arg.DemoID,
		arg.RoundNumber,
		arg.StartTick,
		arg.EndTick,
		arg.WinnerSide,
		arg.WinReason,
		arg.CtScore,
		arg.TScore,
		arg.IsOvertime,
	)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.DemoID,
		&i.RoundNumber,
		&i.StartTick,
		&i.EndTick,
		&i.WinnerSide,
		&i.WinReason,
		&i.CtScore,
		&i.TScore,
		&i.IsOvertime,
	)
	return i, err
}

const deleteRoundsByDemoID = `-- name: DeleteRoundsByDemoID :exec
DELETE FROM rounds WHERE demo_id = $1
`

func (q *Queries) DeleteRoundsByDemoID(ctx context.Context, demoID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRoundsByDemoID, demoID)
	return err
}

const getRoundByDemoAndNumber = `-- name: GetRoundByDemoAndNumber :one
SELECT id, demo_id, round_number, start_tick, end_tick, winner_side, win_reason, ct_score, t_score, is_overtime FROM rounds WHERE demo_id = $1 AND round_number = $2
`

type GetRoundByDemoAndNumberParams struct {
	DemoID      uuid.UUID
	RoundNumber int16
}

func (q *Queries) GetRoundByDemoAndNumber(ctx context.Context, arg GetRoundByDemoAndNumberParams) (Round, error) {
	row := q.db.QueryRowContext(ctx, getRoundByDemoAndNumber, arg.DemoID, arg.RoundNumber)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.DemoID,
		&i.RoundNumber,
		&i.StartTick,
		&i.EndTick,
		&i.WinnerSide,
		&i.WinReason,
		&i.CtScore,
		&i.TScore,
		&i.IsOvertime,
	)
	return i, err
}

const getRoundsByDemoID = `-- name: GetRoundsByDemoID :many
SELECT id, demo_id, round_number, start_tick, end_tick, winner_side, win_reason, ct_score, t_score, is_overtime FROM rounds WHERE demo_id = $1 ORDER BY round_number
`

func (q *Queries) GetRoundsByDemoID(ctx context.Context, demoID uuid.UUID) ([]Round, error) {
	rows, err := q.db.QueryContext(ctx, getRoundsByDemoID, demoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Round
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.RoundNumber,
			&i.StartTick,
			&i.EndTick,
			&i.WinnerSide,
			&i.WinReason,
			&i.CtScore,
			&i.TScore,
			&i.IsOvertime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
