// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: strategy_boards.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createStrategyBoard = `-- name: CreateStrategyBoard :one
INSERT INTO strategy_boards (user_id, title, map_name)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, map_name, yjs_state, share_mode, share_token, created_at, updated_at
`

type CreateStrategyBoardParams struct {
	UserID  uuid.UUID
	Title   string
	MapName string
}

func (q *Queries) CreateStrategyBoard(ctx context.Context, arg CreateStrategyBoardParams) (StrategyBoard, error) {
	row := q.db.QueryRowContext(ctx, createStrategyBoard, arg.UserID, arg.Title, arg.MapName)
	var i StrategyBoard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.MapName,
		&i.YjsState,
		&i.ShareMode,
		&i.ShareToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStrategyBoard = `-- name: DeleteStrategyBoard :exec
DELETE FROM strategy_boards WHERE id = $1
`

func (q *Queries) DeleteStrategyBoard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStrategyBoard, id)
	return err
}

const getStrategyBoardByID = `-- name: GetStrategyBoardByID :one
SELECT id, user_id, title, map_name, yjs_state, share_mode, share_token, created_at, updated_at FROM strategy_boards WHERE id = $1
`

func (q *Queries) GetStrategyBoardByID(ctx context.Context, id uuid.UUID) (StrategyBoard, error) {
	row := q.db.QueryRowContext(ctx, getStrategyBoardByID, id)
	var i StrategyBoard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.MapName,
		&i.YjsState,
		&i.ShareMode,
		&i.ShareToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStrategyBoardByShareToken = `-- name: GetStrategyBoardByShareToken :one
SELECT id, user_id, title, map_name, yjs_state, share_mode, share_token, created_at, updated_at FROM strategy_boards WHERE share_token = $1
`

func (q *Queries) GetStrategyBoardByShareToken(ctx context.Context, shareToken sql.NullString) (StrategyBoard, error) {
	row := q.db.QueryRowContext(ctx, getStrategyBoardByShareToken, shareToken)
	var i StrategyBoard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.MapName,
		&i.YjsState,
		&i.ShareMode,
		&i.ShareToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStrategyBoardsByUserID = `-- name: ListStrategyBoardsByUserID :many
SELECT id, user_id, title, map_name, yjs_state, share_mode, share_token, created_at, updated_at FROM strategy_boards WHERE user_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListStrategyBoardsByUserID(ctx context.Context, userID uuid.UUID) ([]StrategyBoard, error) {
	rows, err := q.db.QueryContext(ctx, listStrategyBoardsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StrategyBoard
	for rows.Next() {
		var i StrategyBoard
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.MapName,
			&i.YjsState,
			&i.ShareMode,
			&i.ShareToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStrategyBoardShareToken = `-- name: SetStrategyBoardShareToken :one
UPDATE strategy_boards SET share_token = $2, updated_at = NOW() WHERE id = $1
RETURNING id, user_id, title, map_name, yjs_state, share_mode, share_token, created_at, updated_at
`

type SetStrategyBoardShareTokenParams struct {
	ID         uuid.UUID
	ShareToken sql.NullString
}

func (q *Queries) SetStrategyBoardShareToken(ctx context.Context, arg SetStrategyBoardShareTokenParams) (StrategyBoard, error) {
	row := q.db.QueryRowContext(ctx, setStrategyBoardShareToken, arg.ID, arg.ShareToken)
	var i StrategyBoard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.MapName,
		&i.YjsState,
		&i.ShareMode,
		&i.ShareToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStrategyBoard = `-- name: UpdateStrategyBoard :one
UPDATE strategy_boards SET
    title = $2,
    map_name = $3,
    share_mode = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, map_name, yjs_state, share_mode, share_token, created_at, updated_at
`

type UpdateStrategyBoardParams struct {
	ID        uuid.UUID
	Title     string
	MapName   string
	ShareMode string
}

func (q *Queries) UpdateStrategyBoard(ctx context.Context, arg UpdateStrategyBoardParams) (StrategyBoard, error) {
	row := q.db.QueryRowContext(ctx, updateStrategyBoard,
		arg.ID,
		arg.Title,
		arg.MapName,
		arg.ShareMode,
	)
	var i StrategyBoard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.MapName,
		&i.YjsState,
		&i.ShareMode,
		&i.ShareToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStrategyBoardYjsState = `-- name: UpdateStrategyBoardYjsState :exec
UPDATE strategy_boards SET yjs_state = $2, updated_at = NOW() WHERE id = $1
`

type UpdateStrategyBoardYjsStateParams struct {
	ID       uuid.UUID
	YjsState []byte
}

func (q *Queries) UpdateStrategyBoardYjsState(ctx context.Context, arg UpdateStrategyBoardYjsStateParams) error {
	_, err := q.db.ExecContext(ctx, updateStrategyBoardYjsState, arg.ID, arg.YjsState)
	return err
}
