// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (faceit_id, nickname, avatar_url, faceit_elo, faceit_level, country)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, faceit_id, nickname, avatar_url, faceit_elo, faceit_level, country, created_at, updated_at
`

type CreateUserParams struct {
	FaceitID    string
	Nickname    string
	AvatarUrl   sql.NullString
	FaceitElo   sql.NullInt32
	FaceitLevel sql.NullInt16
	Country     sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FaceitID,
		arg.Nickname,
		arg.AvatarUrl,
		arg.FaceitElo,
		arg.FaceitLevel,
		arg.Country,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FaceitID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.FaceitElo,
		&i.FaceitLevel,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByFaceitID = `-- name: GetUserByFaceitID :one
SELECT id, faceit_id, nickname, avatar_url, faceit_elo, faceit_level, country, created_at, updated_at FROM users WHERE faceit_id = $1
`

func (q *Queries) GetUserByFaceitID(ctx context.Context, faceitID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByFaceitID, faceitID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FaceitID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.FaceitElo,
		&i.FaceitLevel,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, faceit_id, nickname, avatar_url, faceit_elo, faceit_level, country, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FaceitID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.FaceitElo,
		&i.FaceitLevel,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    nickname = $2,
    avatar_url = $3,
    faceit_elo = $4,
    faceit_level = $5,
    country = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, faceit_id, nickname, avatar_url, faceit_elo, faceit_level, country, created_at, updated_at
`

type UpdateUserParams struct {
	ID          uuid.UUID
	Nickname    string
	AvatarUrl   sql.NullString
	FaceitElo   sql.NullInt32
	FaceitLevel sql.NullInt16
	Country     sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Nickname,
		arg.AvatarUrl,
		arg.FaceitElo,
		arg.FaceitLevel,
		arg.Country,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FaceitID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.FaceitElo,
		&i.FaceitLevel,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
