// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analysis_mistakes.sql

package store

import (
	"context"
)

const createAnalysisMistake = `-- name: CreateAnalysisMistake :exec
INSERT INTO analysis_mistakes (demo_id, steam_id, round_number, tick, kind, extras_json)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type CreateAnalysisMistakeParams struct {
	DemoID      int64
	SteamID     string
	RoundNumber int64
	Tick        int64
	Kind        string
	ExtrasJson  string
}

func (q *Queries) CreateAnalysisMistake(ctx context.Context, arg CreateAnalysisMistakeParams) error {
	_, err := q.db.ExecContext(ctx, createAnalysisMistake,
		arg.DemoID,
		arg.SteamID,
		arg.RoundNumber,
		arg.Tick,
		arg.Kind,
		arg.ExtrasJson,
	)
	return err
}

const deleteAnalysisMistakesByDemoID = `-- name: DeleteAnalysisMistakesByDemoID :exec
DELETE FROM analysis_mistakes
WHERE demo_id = ?1
`

func (q *Queries) DeleteAnalysisMistakesByDemoID(ctx context.Context, demoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAnalysisMistakesByDemoID, demoID)
	return err
}

const listAnalysisMistakesByDemoIDAndSteamID = `-- name: ListAnalysisMistakesByDemoIDAndSteamID :many
SELECT id, demo_id, steam_id, round_number, tick, kind, extras_json, created_at
FROM analysis_mistakes
WHERE demo_id = ?1
  AND steam_id = ?2
ORDER BY tick ASC, id ASC
`

type ListAnalysisMistakesByDemoIDAndSteamIDParams struct {
	DemoID  int64
	SteamID string
}

// Returns every mistake row for (demo, player), ordered chronologically so the
// viewer side panel can render them as-is.
func (q *Queries) ListAnalysisMistakesByDemoIDAndSteamID(ctx context.Context, arg ListAnalysisMistakesByDemoIDAndSteamIDParams) ([]AnalysisMistake, error) {
	rows, err := q.db.QueryContext(ctx, listAnalysisMistakesByDemoIDAndSteamID, arg.DemoID, arg.SteamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalysisMistake
	for rows.Next() {
		var i AnalysisMistake
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.SteamID,
			&i.RoundNumber,
			&i.Tick,
			&i.Kind,
			&i.ExtrasJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
