// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analysis_duels.sql

package store

import (
	"context"
	"database/sql"
)

const createAnalysisDuel = `-- name: CreateAnalysisDuel :one
INSERT INTO analysis_duels (
    demo_id, round_number, round_id,
    attacker_steam, victim_steam,
    start_tick, end_tick,
    outcome, end_reason,
    hit_confirmed, hurt_count, shot_count,
    extras_json
)
VALUES (
    ?1, ?2, ?3,
    ?4, ?5,
    ?6, ?7,
    ?8, ?9,
    ?10, ?11, ?12,
    ?13
)
RETURNING id
`

type CreateAnalysisDuelParams struct {
	DemoID        int64
	RoundNumber   int64
	RoundID       sql.NullInt64
	AttackerSteam string
	VictimSteam   string
	StartTick     int64
	EndTick       int64
	Outcome       string
	EndReason     string
	HitConfirmed  int64
	HurtCount     int64
	ShotCount     int64
	ExtrasJson    string
}

// Returns the inserted rowid so the persistence layer can map detector
// LocalIDs to database primary keys when wiring analysis_mistakes.duel_id.
func (q *Queries) CreateAnalysisDuel(ctx context.Context, arg CreateAnalysisDuelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAnalysisDuel,
		arg.DemoID,
		arg.RoundNumber,
		arg.RoundID,
		arg.AttackerSteam,
		arg.VictimSteam,
		arg.StartTick,
		arg.EndTick,
		arg.Outcome,
		arg.EndReason,
		arg.HitConfirmed,
		arg.HurtCount,
		arg.ShotCount,
		arg.ExtrasJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAnalysisDuelsByDemoID = `-- name: DeleteAnalysisDuelsByDemoID :exec
DELETE FROM analysis_duels
WHERE demo_id = ?1
`

func (q *Queries) DeleteAnalysisDuelsByDemoID(ctx context.Context, demoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAnalysisDuelsByDemoID, demoID)
	return err
}

const getAnalysisDuelByID = `-- name: GetAnalysisDuelByID :one
SELECT id, demo_id, round_number, round_id,
       attacker_steam, victim_steam,
       start_tick, end_tick,
       outcome, end_reason,
       hit_confirmed, hurt_count, shot_count,
       mutual_duel_id, extras_json, created_at
FROM analysis_duels
WHERE id = ?1
`

func (q *Queries) GetAnalysisDuelByID(ctx context.Context, id int64) (AnalysisDuel, error) {
	row := q.db.QueryRowContext(ctx, getAnalysisDuelByID, id)
	var i AnalysisDuel
	err := row.Scan(
		&i.ID,
		&i.DemoID,
		&i.RoundNumber,
		&i.RoundID,
		&i.AttackerSteam,
		&i.VictimSteam,
		&i.StartTick,
		&i.EndTick,
		&i.Outcome,
		&i.EndReason,
		&i.HitConfirmed,
		&i.HurtCount,
		&i.ShotCount,
		&i.MutualDuelID,
		&i.ExtrasJson,
		&i.CreatedAt,
	)
	return i, err
}

const listAnalysisDuelsByDemoID = `-- name: ListAnalysisDuelsByDemoID :many
SELECT id, demo_id, round_number, round_id,
       attacker_steam, victim_steam,
       start_tick, end_tick,
       outcome, end_reason,
       hit_confirmed, hurt_count, shot_count,
       mutual_duel_id, extras_json, created_at
FROM analysis_duels
WHERE demo_id = ?1
ORDER BY round_number ASC, start_tick ASC, id ASC
`

func (q *Queries) ListAnalysisDuelsByDemoID(ctx context.Context, demoID int64) ([]AnalysisDuel, error) {
	rows, err := q.db.QueryContext(ctx, listAnalysisDuelsByDemoID, demoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalysisDuel
	for rows.Next() {
		var i AnalysisDuel
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.RoundNumber,
			&i.RoundID,
			&i.AttackerSteam,
			&i.VictimSteam,
			&i.StartTick,
			&i.EndTick,
			&i.Outcome,
			&i.EndReason,
			&i.HitConfirmed,
			&i.HurtCount,
			&i.ShotCount,
			&i.MutualDuelID,
			&i.ExtrasJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalysisDuelsByDemoIDAndSteamID = `-- name: ListAnalysisDuelsByDemoIDAndSteamID :many
SELECT id, demo_id, round_number, round_id,
       attacker_steam, victim_steam,
       start_tick, end_tick,
       outcome, end_reason,
       hit_confirmed, hurt_count, shot_count,
       mutual_duel_id, extras_json, created_at
FROM analysis_duels
WHERE demo_id = ?1
  AND (attacker_steam = ?2 OR victim_steam = ?2)
ORDER BY round_number ASC, start_tick ASC, id ASC
`

type ListAnalysisDuelsByDemoIDAndSteamIDParams struct {
	DemoID  int64
	SteamID string
}

// Returns duels where the supplied steamID is either the attacker or the
// victim, sorted chronologically. Powers the per-player duel lane on the
// viewer's round timeline.
func (q *Queries) ListAnalysisDuelsByDemoIDAndSteamID(ctx context.Context, arg ListAnalysisDuelsByDemoIDAndSteamIDParams) ([]AnalysisDuel, error) {
	rows, err := q.db.QueryContext(ctx, listAnalysisDuelsByDemoIDAndSteamID, arg.DemoID, arg.SteamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalysisDuel
	for rows.Next() {
		var i AnalysisDuel
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.RoundNumber,
			&i.RoundID,
			&i.AttackerSteam,
			&i.VictimSteam,
			&i.StartTick,
			&i.EndTick,
			&i.Outcome,
			&i.EndReason,
			&i.HitConfirmed,
			&i.HurtCount,
			&i.ShotCount,
			&i.MutualDuelID,
			&i.ExtrasJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalysisMistakesByDuelID = `-- name: ListAnalysisMistakesByDuelID :many
SELECT id, demo_id, steam_id, round_number, round_id, tick, kind, category, severity, extras_json, duel_id, created_at
FROM analysis_mistakes
WHERE duel_id = ?1
ORDER BY tick ASC, id ASC
`

type ListAnalysisMistakesByDuelIDRow struct {
	ID          int64
	DemoID      int64
	SteamID     string
	RoundNumber int64
	RoundID     sql.NullInt64
	Tick        int64
	Kind        string
	Category    string
	Severity    int64
	ExtrasJson  string
	DuelID      sql.NullInt64
	CreatedAt   string
}

// Used by GetDuelContext to materialise the tooltip / popover content
// (the mistakes inside a duel) with one query.
func (q *Queries) ListAnalysisMistakesByDuelID(ctx context.Context, duelID sql.NullInt64) ([]ListAnalysisMistakesByDuelIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listAnalysisMistakesByDuelID, duelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnalysisMistakesByDuelIDRow
	for rows.Next() {
		var i ListAnalysisMistakesByDuelIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.SteamID,
			&i.RoundNumber,
			&i.RoundID,
			&i.Tick,
			&i.Kind,
			&i.Category,
			&i.Severity,
			&i.ExtrasJson,
			&i.DuelID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnalysisDuelMutual = `-- name: UpdateAnalysisDuelMutual :exec
UPDATE analysis_duels SET mutual_duel_id = ?1 WHERE id = ?2
`

type UpdateAnalysisDuelMutualParams struct {
	MutualDuelID sql.NullInt64
	ID           int64
}

// Backfills mutual_duel_id once peer rows have ids. Runs in the same tx
// as CreateAnalysisDuel so the link is atomic with insertion.
func (q *Queries) UpdateAnalysisDuelMutual(ctx context.Context, arg UpdateAnalysisDuelMutualParams) error {
	_, err := q.db.ExecContext(ctx, updateAnalysisDuelMutual, arg.MutualDuelID, arg.ID)
	return err
}
