// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact_mistakes.sql

package store

import (
	"context"
	"database/sql"
)

const deleteContactMistakesByDemoID = `-- name: DeleteContactMistakesByDemoID :exec
DELETE FROM contact_mistakes
WHERE contact_id IN (
    SELECT id FROM contact_moments WHERE demo_id = ?1
)
`

func (q *Queries) DeleteContactMistakesByDemoID(ctx context.Context, demoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteContactMistakesByDemoID, demoID)
	return err
}

const insertContactMistake = `-- name: InsertContactMistake :exec
INSERT OR REPLACE INTO contact_mistakes (
    contact_id,
    kind,
    category,
    severity,
    phase,
    tick,
    extras_json,
    detector_version
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8
)
`

type InsertContactMistakeParams struct {
	ContactID       int64
	Kind            string
	Category        string
	Severity        int64
	Phase           string
	Tick            sql.NullInt64
	ExtrasJson      string
	DetectorVersion int64
}

func (q *Queries) InsertContactMistake(ctx context.Context, arg InsertContactMistakeParams) error {
	_, err := q.db.ExecContext(ctx, insertContactMistake,
		arg.ContactID,
		arg.Kind,
		arg.Category,
		arg.Severity,
		arg.Phase,
		arg.Tick,
		arg.ExtrasJson,
		arg.DetectorVersion,
	)
	return err
}

const listContactMistakesByContact = `-- name: ListContactMistakesByContact :many
SELECT contact_id, kind, category, severity, phase, tick, extras_json, detector_version
FROM contact_mistakes
WHERE contact_id = ?1
ORDER BY phase ASC, severity DESC, tick ASC
`

func (q *Queries) ListContactMistakesByContact(ctx context.Context, contactID int64) ([]ContactMistake, error) {
	rows, err := q.db.QueryContext(ctx, listContactMistakesByContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactMistake
	for rows.Next() {
		var i ContactMistake
		if err := rows.Scan(
			&i.ContactID,
			&i.Kind,
			&i.Category,
			&i.Severity,
			&i.Phase,
			&i.Tick,
			&i.ExtrasJson,
			&i.DetectorVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxDetectorVersionForDemo = `-- name: MaxDetectorVersionForDemo :one
SELECT COALESCE(MAX(detector_version), 0) AS version
FROM contact_mistakes
WHERE contact_id IN (SELECT id FROM contact_moments WHERE demo_id = ?1)
`

// Phase 3 rebuild gate: if MAX < compiled DetectorVersion, rewrite for demo.
func (q *Queries) MaxDetectorVersionForDemo(ctx context.Context, demoID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxDetectorVersionForDemo, demoID)
	var version interface{}
	err := row.Scan(&version)
	return version, err
}
