// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact_moments.sql

package store

import (
	"context"
)

const deleteContactMomentsByDemoID = `-- name: DeleteContactMomentsByDemoID :exec
DELETE FROM contact_moments WHERE demo_id = ?1
`

func (q *Queries) DeleteContactMomentsByDemoID(ctx context.Context, demoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteContactMomentsByDemoID, demoID)
	return err
}

const insertContactMoment = `-- name: InsertContactMoment :one
INSERT INTO contact_moments (
    demo_id,
    round_id,
    subject_steam,
    t_first,
    t_last,
    t_pre,
    t_post,
    enemies_json,
    outcome,
    signal_count,
    extras_json,
    builder_version
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6, ?7,
    ?8, ?9, ?10,
    ?11, ?12
)
RETURNING id
`

type InsertContactMomentParams struct {
	DemoID         int64
	RoundID        int64
	SubjectSteam   string
	TFirst         int64
	TLast          int64
	TPre           int64
	TPost          int64
	EnemiesJson    string
	Outcome        string
	SignalCount    int64
	ExtrasJson     string
	BuilderVersion int64
}

func (q *Queries) InsertContactMoment(ctx context.Context, arg InsertContactMomentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertContactMoment,
		arg.DemoID,
		arg.RoundID,
		arg.SubjectSteam,
		arg.TFirst,
		arg.TLast,
		arg.TPre,
		arg.TPost,
		arg.EnemiesJson,
		arg.Outcome,
		arg.SignalCount,
		arg.ExtrasJson,
		arg.BuilderVersion,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listContactsByDemoRoundSubject = `-- name: ListContactsByDemoRoundSubject :many
SELECT id, demo_id, round_id, subject_steam,
       t_first, t_last, t_pre, t_post,
       enemies_json, outcome, signal_count,
       extras_json, builder_version, created_at
FROM contact_moments
WHERE demo_id = ?1
  AND round_id = ?2
  AND subject_steam = ?3
ORDER BY t_first ASC, id ASC
`

type ListContactsByDemoRoundSubjectParams struct {
	DemoID       int64
	RoundID      int64
	SubjectSteam string
}

// Phase 3/4 read path: every contact in one round for one subject.
func (q *Queries) ListContactsByDemoRoundSubject(ctx context.Context, arg ListContactsByDemoRoundSubjectParams) ([]ContactMoment, error) {
	rows, err := q.db.QueryContext(ctx, listContactsByDemoRoundSubject, arg.DemoID, arg.RoundID, arg.SubjectSteam)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactMoment
	for rows.Next() {
		var i ContactMoment
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.RoundID,
			&i.SubjectSteam,
			&i.TFirst,
			&i.TLast,
			&i.TPre,
			&i.TPost,
			&i.EnemiesJson,
			&i.Outcome,
			&i.SignalCount,
			&i.ExtrasJson,
			&i.BuilderVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByDemoSubject = `-- name: ListContactsByDemoSubject :many
SELECT id, demo_id, round_id, subject_steam,
       t_first, t_last, t_pre, t_post,
       enemies_json, outcome, signal_count,
       extras_json, builder_version, created_at
FROM contact_moments
WHERE demo_id = ?1
  AND subject_steam = ?2
ORDER BY t_first ASC, id ASC
`

type ListContactsByDemoSubjectParams struct {
	DemoID       int64
	SubjectSteam string
}

// Phase 4 read path: every contact for (demo, subject), ordered chronologically.
func (q *Queries) ListContactsByDemoSubject(ctx context.Context, arg ListContactsByDemoSubjectParams) ([]ContactMoment, error) {
	rows, err := q.db.QueryContext(ctx, listContactsByDemoSubject, arg.DemoID, arg.SubjectSteam)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactMoment
	for rows.Next() {
		var i ContactMoment
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.RoundID,
			&i.SubjectSteam,
			&i.TFirst,
			&i.TLast,
			&i.TPre,
			&i.TPost,
			&i.EnemiesJson,
			&i.Outcome,
			&i.SignalCount,
			&i.ExtrasJson,
			&i.BuilderVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxBuilderVersionForDemo = `-- name: MaxBuilderVersionForDemo :one
SELECT COALESCE(MAX(builder_version), 0) AS version
FROM contact_moments
WHERE demo_id = ?1
`

// Phase 3 rebuild gate: if MAX < compiled builder_version, rebuild for demo.
func (q *Queries) MaxBuilderVersionForDemo(ctx context.Context, demoID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxBuilderVersionForDemo, demoID)
	var version interface{}
	err := row.Scan(&version)
	return version, err
}
