// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: demos.sql

package store

import (
	"context"
)

const countDemos = `-- name: CountDemos :one
SELECT count(*) FROM demos
`

func (q *Queries) CountDemos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDemos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDemo = `-- name: CreateDemo :one
INSERT INTO demos (map_name, file_path, file_size, status, match_date)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, map_name, file_path, file_size, status, total_ticks, tick_rate, duration_secs, match_date, created_at
`

type CreateDemoParams struct {
	MapName   string
	FilePath  string
	FileSize  int64
	Status    string
	MatchDate string
}

func (q *Queries) CreateDemo(ctx context.Context, arg CreateDemoParams) (Demo, error) {
	row := q.db.QueryRowContext(ctx, createDemo,
		arg.MapName,
		arg.FilePath,
		arg.FileSize,
		arg.Status,
		arg.MatchDate,
	)
	var i Demo
	err := row.Scan(
		&i.ID,
		&i.MapName,
		&i.FilePath,
		&i.FileSize,
		&i.Status,
		&i.TotalTicks,
		&i.TickRate,
		&i.DurationSecs,
		&i.MatchDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDemo = `-- name: DeleteDemo :exec
DELETE FROM demos WHERE id = ?1
`

func (q *Queries) DeleteDemo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDemo, id)
	return err
}

const getDemoByID = `-- name: GetDemoByID :one
SELECT id, map_name, file_path, file_size, status, total_ticks, tick_rate, duration_secs, match_date, created_at FROM demos WHERE id = ?1
`

func (q *Queries) GetDemoByID(ctx context.Context, id int64) (Demo, error) {
	row := q.db.QueryRowContext(ctx, getDemoByID, id)
	var i Demo
	err := row.Scan(
		&i.ID,
		&i.MapName,
		&i.FilePath,
		&i.FileSize,
		&i.Status,
		&i.TotalTicks,
		&i.TickRate,
		&i.DurationSecs,
		&i.MatchDate,
		&i.CreatedAt,
	)
	return i, err
}

const listDemos = `-- name: ListDemos :many
SELECT id, map_name, file_path, file_size, status, total_ticks, tick_rate, duration_secs, match_date, created_at FROM demos
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?1
`

type ListDemosParams struct {
	OffsetVal int64
	LimitVal  int64
}

func (q *Queries) ListDemos(ctx context.Context, arg ListDemosParams) ([]Demo, error) {
	rows, err := q.db.QueryContext(ctx, listDemos, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Demo
	for rows.Next() {
		var i Demo
		if err := rows.Scan(
			&i.ID,
			&i.MapName,
			&i.FilePath,
			&i.FileSize,
			&i.Status,
			&i.TotalTicks,
			&i.TickRate,
			&i.DurationSecs,
			&i.MatchDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDemoAfterParse = `-- name: UpdateDemoAfterParse :one
UPDATE demos SET
    status = 'ready',
    map_name = ?1,
    total_ticks = ?2,
    tick_rate = ?3,
    duration_secs = ?4
WHERE id = ?5
RETURNING id, map_name, file_path, file_size, status, total_ticks, tick_rate, duration_secs, match_date, created_at
`

type UpdateDemoAfterParseParams struct {
	MapName      string
	TotalTicks   int64
	TickRate     float64
	DurationSecs int64
	ID           int64
}

func (q *Queries) UpdateDemoAfterParse(ctx context.Context, arg UpdateDemoAfterParseParams) (Demo, error) {
	row := q.db.QueryRowContext(ctx, updateDemoAfterParse,
		arg.MapName,
		arg.TotalTicks,
		arg.TickRate,
		arg.DurationSecs,
		arg.ID,
	)
	var i Demo
	err := row.Scan(
		&i.ID,
		&i.MapName,
		&i.FilePath,
		&i.FileSize,
		&i.Status,
		&i.TotalTicks,
		&i.TickRate,
		&i.DurationSecs,
		&i.MatchDate,
		&i.CreatedAt,
	)
	return i, err
}

const updateDemoStatus = `-- name: UpdateDemoStatus :one
UPDATE demos SET status = ?1 WHERE id = ?2
RETURNING id, map_name, file_path, file_size, status, total_ticks, tick_rate, duration_secs, match_date, created_at
`

type UpdateDemoStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) UpdateDemoStatus(ctx context.Context, arg UpdateDemoStatusParams) (Demo, error) {
	row := q.db.QueryRowContext(ctx, updateDemoStatus, arg.Status, arg.ID)
	var i Demo
	err := row.Scan(
		&i.ID,
		&i.MapName,
		&i.FilePath,
		&i.FileSize,
		&i.Status,
		&i.TotalTicks,
		&i.TickRate,
		&i.DurationSecs,
		&i.MatchDate,
		&i.CreatedAt,
	)
	return i, err
}
