// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: faceit_matches.sql

package store

import (
	"context"
	"database/sql"
)

const countFaceitMatchesByUserID = `-- name: CountFaceitMatchesByUserID :one
SELECT COUNT(*) FROM faceit_matches WHERE user_id = ?1
`

func (q *Queries) CountFaceitMatchesByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFaceitMatchesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFaceitMatchesFiltered = `-- name: CountFaceitMatchesFiltered :one
SELECT COUNT(*) FROM faceit_matches
WHERE user_id = ?1
  AND (?2 IS NULL OR map_name = ?2)
  AND (?3 IS NULL OR result = ?3)
`

type CountFaceitMatchesFilteredParams struct {
	UserID  int64
	MapName interface{}
	Result  interface{}
}

func (q *Queries) CountFaceitMatchesFiltered(ctx context.Context, arg CountFaceitMatchesFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFaceitMatchesFiltered, arg.UserID, arg.MapName, arg.Result)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFaceitMatch = `-- name: CreateFaceitMatch :one
INSERT INTO faceit_matches (user_id, faceit_match_id, map_name, score_team, score_opponent, result, elo_before, elo_after, kills, deaths, assists, demo_url, demo_id, played_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14)
RETURNING id, user_id, faceit_match_id, map_name, score_team, score_opponent, result, elo_before, elo_after, kills, deaths, assists, demo_url, demo_id, played_at, created_at
`

type CreateFaceitMatchParams struct {
	UserID        int64
	FaceitMatchID string
	MapName       string
	ScoreTeam     int64
	ScoreOpponent int64
	Result        string
	EloBefore     int64
	EloAfter      int64
	Kills         int64
	Deaths        int64
	Assists       int64
	DemoUrl       string
	DemoID        sql.NullInt64
	PlayedAt      string
}

func (q *Queries) CreateFaceitMatch(ctx context.Context, arg CreateFaceitMatchParams) (FaceitMatch, error) {
	row := q.db.QueryRowContext(ctx, createFaceitMatch,
		arg.UserID,
		arg.FaceitMatchID,
		arg.MapName,
		arg.ScoreTeam,
		arg.ScoreOpponent,
		arg.Result,
		arg.EloBefore,
		arg.EloAfter,
		arg.Kills,
		arg.Deaths,
		arg.Assists,
		arg.DemoUrl,
		arg.DemoID,
		arg.PlayedAt,
	)
	var i FaceitMatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FaceitMatchID,
		&i.MapName,
		&i.ScoreTeam,
		&i.ScoreOpponent,
		&i.Result,
		&i.EloBefore,
		&i.EloAfter,
		&i.Kills,
		&i.Deaths,
		&i.Assists,
		&i.DemoUrl,
		&i.DemoID,
		&i.PlayedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFaceitMatchesByUserID = `-- name: DeleteFaceitMatchesByUserID :exec
DELETE FROM faceit_matches WHERE user_id = ?1
`

func (q *Queries) DeleteFaceitMatchesByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFaceitMatchesByUserID, userID)
	return err
}

const getCurrentStreak = `-- name: GetCurrentStreak :many
SELECT result FROM faceit_matches
WHERE user_id = ?1
ORDER BY played_at DESC
LIMIT 30
`

func (q *Queries) GetCurrentStreak(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCurrentStreak, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var result string
		if err := rows.Scan(&result); err != nil {
			return nil, err
		}
		items = append(items, result)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEloHistory = `-- name: GetEloHistory :many
SELECT id, faceit_match_id, map_name, elo_after, played_at
FROM faceit_matches
WHERE user_id = ?1 AND played_at >= ?2
ORDER BY played_at ASC
`

type GetEloHistoryParams struct {
	UserID int64
	Since  string
}

type GetEloHistoryRow struct {
	ID            int64
	FaceitMatchID string
	MapName       string
	EloAfter      int64
	PlayedAt      string
}

func (q *Queries) GetEloHistory(ctx context.Context, arg GetEloHistoryParams) ([]GetEloHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getEloHistory, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEloHistoryRow
	for rows.Next() {
		var i GetEloHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.FaceitMatchID,
			&i.MapName,
			&i.EloAfter,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingFaceitMatchIDs = `-- name: GetExistingFaceitMatchIDs :many
SELECT faceit_match_id FROM faceit_matches WHERE user_id = ?1
`

func (q *Queries) GetExistingFaceitMatchIDs(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getExistingFaceitMatchIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var faceit_match_id string
		if err := rows.Scan(&faceit_match_id); err != nil {
			return nil, err
		}
		items = append(items, faceit_match_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFaceitMatchByID = `-- name: GetFaceitMatchByID :one
SELECT id, user_id, faceit_match_id, map_name, score_team, score_opponent, result, elo_before, elo_after, kills, deaths, assists, demo_url, demo_id, played_at, created_at FROM faceit_matches WHERE id = ?1
`

func (q *Queries) GetFaceitMatchByID(ctx context.Context, id int64) (FaceitMatch, error) {
	row := q.db.QueryRowContext(ctx, getFaceitMatchByID, id)
	var i FaceitMatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FaceitMatchID,
		&i.MapName,
		&i.ScoreTeam,
		&i.ScoreOpponent,
		&i.Result,
		&i.EloBefore,
		&i.EloAfter,
		&i.Kills,
		&i.Deaths,
		&i.Assists,
		&i.DemoUrl,
		&i.DemoID,
		&i.PlayedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFaceitMatchesByUserID = `-- name: GetFaceitMatchesByUserID :many
SELECT id, user_id, faceit_match_id, map_name, score_team, score_opponent, result, elo_before, elo_after, kills, deaths, assists, demo_url, demo_id, played_at, created_at FROM faceit_matches
WHERE user_id = ?1
ORDER BY played_at DESC
LIMIT ?3 OFFSET ?2
`

type GetFaceitMatchesByUserIDParams struct {
	UserID    int64
	OffsetVal int64
	LimitVal  int64
}

func (q *Queries) GetFaceitMatchesByUserID(ctx context.Context, arg GetFaceitMatchesByUserIDParams) ([]FaceitMatch, error) {
	rows, err := q.db.QueryContext(ctx, getFaceitMatchesByUserID, arg.UserID, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FaceitMatch
	for rows.Next() {
		var i FaceitMatch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FaceitMatchID,
			&i.MapName,
			&i.ScoreTeam,
			&i.ScoreOpponent,
			&i.Result,
			&i.EloBefore,
			&i.EloAfter,
			&i.Kills,
			&i.Deaths,
			&i.Assists,
			&i.DemoUrl,
			&i.DemoID,
			&i.PlayedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFaceitMatchesFiltered = `-- name: GetFaceitMatchesFiltered :many
SELECT id, user_id, faceit_match_id, map_name, score_team, score_opponent, result, elo_before, elo_after, kills, deaths, assists, demo_url, demo_id, played_at, created_at FROM faceit_matches
WHERE user_id = ?1
  AND (?2 IS NULL OR map_name = ?2)
  AND (?3 IS NULL OR result = ?3)
ORDER BY played_at DESC
LIMIT ?5 OFFSET ?4
`

type GetFaceitMatchesFilteredParams struct {
	UserID    int64
	MapName   interface{}
	Result    interface{}
	OffsetVal int64
	LimitVal  int64
}

func (q *Queries) GetFaceitMatchesFiltered(ctx context.Context, arg GetFaceitMatchesFilteredParams) ([]FaceitMatch, error) {
	rows, err := q.db.QueryContext(ctx, getFaceitMatchesFiltered,
		arg.UserID,
		arg.MapName,
		arg.Result,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FaceitMatch
	for rows.Next() {
		var i FaceitMatch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FaceitMatchID,
			&i.MapName,
			&i.ScoreTeam,
			&i.ScoreOpponent,
			&i.Result,
			&i.EloBefore,
			&i.EloAfter,
			&i.Kills,
			&i.Deaths,
			&i.Assists,
			&i.DemoUrl,
			&i.DemoID,
			&i.PlayedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkFaceitMatchToDemo = `-- name: LinkFaceitMatchToDemo :one
UPDATE faceit_matches SET demo_id = ?1 WHERE id = ?2
RETURNING id, user_id, faceit_match_id, map_name, score_team, score_opponent, result, elo_before, elo_after, kills, deaths, assists, demo_url, demo_id, played_at, created_at
`

type LinkFaceitMatchToDemoParams struct {
	DemoID sql.NullInt64
	ID     int64
}

func (q *Queries) LinkFaceitMatchToDemo(ctx context.Context, arg LinkFaceitMatchToDemoParams) (FaceitMatch, error) {
	row := q.db.QueryRowContext(ctx, linkFaceitMatchToDemo, arg.DemoID, arg.ID)
	var i FaceitMatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FaceitMatchID,
		&i.MapName,
		&i.ScoreTeam,
		&i.ScoreOpponent,
		&i.Result,
		&i.EloBefore,
		&i.EloAfter,
		&i.Kills,
		&i.Deaths,
		&i.Assists,
		&i.DemoUrl,
		&i.DemoID,
		&i.PlayedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertFaceitMatch = `-- name: UpsertFaceitMatch :one
INSERT INTO faceit_matches (user_id, faceit_match_id, map_name, score_team, score_opponent, result, elo_before, elo_after, kills, deaths, assists, demo_url, demo_id, played_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14)
ON CONFLICT (user_id, faceit_match_id) DO NOTHING
RETURNING id, user_id, faceit_match_id, map_name, score_team, score_opponent, result, elo_before, elo_after, kills, deaths, assists, demo_url, demo_id, played_at, created_at
`

type UpsertFaceitMatchParams struct {
	UserID        int64
	FaceitMatchID string
	MapName       string
	ScoreTeam     int64
	ScoreOpponent int64
	Result        string
	EloBefore     int64
	EloAfter      int64
	Kills         int64
	Deaths        int64
	Assists       int64
	DemoUrl       string
	DemoID        sql.NullInt64
	PlayedAt      string
}

func (q *Queries) UpsertFaceitMatch(ctx context.Context, arg UpsertFaceitMatchParams) (FaceitMatch, error) {
	row := q.db.QueryRowContext(ctx, upsertFaceitMatch,
		arg.UserID,
		arg.FaceitMatchID,
		arg.MapName,
		arg.ScoreTeam,
		arg.ScoreOpponent,
		arg.Result,
		arg.EloBefore,
		arg.EloAfter,
		arg.Kills,
		arg.Deaths,
		arg.Assists,
		arg.DemoUrl,
		arg.DemoID,
		arg.PlayedAt,
	)
	var i FaceitMatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FaceitMatchID,
		&i.MapName,
		&i.ScoreTeam,
		&i.ScoreOpponent,
		&i.Result,
		&i.EloBefore,
		&i.EloAfter,
		&i.Kills,
		&i.Deaths,
		&i.Assists,
		&i.DemoUrl,
		&i.DemoID,
		&i.PlayedAt,
		&i.CreatedAt,
	)
	return i, err
}
