// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_events.sql

package store

import (
	"context"
	"database/sql"
)

const createGameEvent = `-- name: CreateGameEvent :one
INSERT INTO game_events (demo_id, round_id, tick, event_type, attacker_steam_id, victim_steam_id, weapon, x, y, z, extra_data)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
RETURNING id, demo_id, round_id, tick, event_type, attacker_steam_id, victim_steam_id, weapon, x, y, z, extra_data
`

type CreateGameEventParams struct {
	DemoID          int64
	RoundID         int64
	Tick            int64
	EventType       string
	AttackerSteamID sql.NullString
	VictimSteamID   sql.NullString
	Weapon          sql.NullString
	X               float64
	Y               float64
	Z               float64
	ExtraData       string
}

func (q *Queries) CreateGameEvent(ctx context.Context, arg CreateGameEventParams) (GameEvent, error) {
	row := q.db.QueryRowContext(ctx, createGameEvent,
		arg.DemoID,
		arg.RoundID,
		arg.Tick,
		arg.EventType,
		arg.AttackerSteamID,
		arg.VictimSteamID,
		arg.Weapon,
		arg.X,
		arg.Y,
		arg.Z,
		arg.ExtraData,
	)
	var i GameEvent
	err := row.Scan(
		&i.ID,
		&i.DemoID,
		&i.RoundID,
		&i.Tick,
		&i.EventType,
		&i.AttackerSteamID,
		&i.VictimSteamID,
		&i.Weapon,
		&i.X,
		&i.Y,
		&i.Z,
		&i.ExtraData,
	)
	return i, err
}

const deleteGameEventsByDemoID = `-- name: DeleteGameEventsByDemoID :exec
DELETE FROM game_events WHERE demo_id = ?1
`

func (q *Queries) DeleteGameEventsByDemoID(ctx context.Context, demoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteGameEventsByDemoID, demoID)
	return err
}

const getGameEventsByDemoAndRound = `-- name: GetGameEventsByDemoAndRound :many
SELECT id, demo_id, round_id, tick, event_type, attacker_steam_id, victim_steam_id, weapon, x, y, z, extra_data FROM game_events WHERE demo_id = ?1 AND round_id = ?2 ORDER BY tick
`

type GetGameEventsByDemoAndRoundParams struct {
	DemoID  int64
	RoundID int64
}

func (q *Queries) GetGameEventsByDemoAndRound(ctx context.Context, arg GetGameEventsByDemoAndRoundParams) ([]GameEvent, error) {
	rows, err := q.db.QueryContext(ctx, getGameEventsByDemoAndRound, arg.DemoID, arg.RoundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameEvent
	for rows.Next() {
		var i GameEvent
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.RoundID,
			&i.Tick,
			&i.EventType,
			&i.AttackerSteamID,
			&i.VictimSteamID,
			&i.Weapon,
			&i.X,
			&i.Y,
			&i.Z,
			&i.ExtraData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameEventsByDemoID = `-- name: GetGameEventsByDemoID :many
SELECT id, demo_id, round_id, tick, event_type, attacker_steam_id, victim_steam_id, weapon, x, y, z, extra_data FROM game_events WHERE demo_id = ?1 ORDER BY tick
`

func (q *Queries) GetGameEventsByDemoID(ctx context.Context, demoID int64) ([]GameEvent, error) {
	rows, err := q.db.QueryContext(ctx, getGameEventsByDemoID, demoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameEvent
	for rows.Next() {
		var i GameEvent
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.RoundID,
			&i.Tick,
			&i.EventType,
			&i.AttackerSteamID,
			&i.VictimSteamID,
			&i.Weapon,
			&i.X,
			&i.Y,
			&i.Z,
			&i.ExtraData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameEventsByType = `-- name: GetGameEventsByType :many
SELECT id, demo_id, round_id, tick, event_type, attacker_steam_id, victim_steam_id, weapon, x, y, z, extra_data FROM game_events WHERE demo_id = ?1 AND event_type = ?2 ORDER BY tick
`

type GetGameEventsByTypeParams struct {
	DemoID    int64
	EventType string
}

func (q *Queries) GetGameEventsByType(ctx context.Context, arg GetGameEventsByTypeParams) ([]GameEvent, error) {
	rows, err := q.db.QueryContext(ctx, getGameEventsByType, arg.DemoID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameEvent
	for rows.Next() {
		var i GameEvent
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.RoundID,
			&i.Tick,
			&i.EventType,
			&i.AttackerSteamID,
			&i.VictimSteamID,
			&i.Weapon,
			&i.X,
			&i.Y,
			&i.Z,
			&i.ExtraData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
