// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: grenade_lineups.sql

package store

import (
	"context"
	"database/sql"
)

const createGrenadeLineup = `-- name: CreateGrenadeLineup :one
INSERT INTO grenade_lineups (demo_id, tick, map_name, grenade_type, throw_x, throw_y, throw_z, throw_yaw, throw_pitch, land_x, land_y, land_z, title, description, tags, is_favorite)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16)
RETURNING id, demo_id, tick, map_name, grenade_type, throw_x, throw_y, throw_z, throw_yaw, throw_pitch, land_x, land_y, land_z, title, description, tags, is_favorite, created_at
`

type CreateGrenadeLineupParams struct {
	DemoID      sql.NullInt64
	Tick        int64
	MapName     string
	GrenadeType string
	ThrowX      float64
	ThrowY      float64
	ThrowZ      float64
	ThrowYaw    float64
	ThrowPitch  float64
	LandX       float64
	LandY       float64
	LandZ       float64
	Title       string
	Description string
	Tags        string
	IsFavorite  int64
}

func (q *Queries) CreateGrenadeLineup(ctx context.Context, arg CreateGrenadeLineupParams) (GrenadeLineup, error) {
	row := q.db.QueryRowContext(ctx, createGrenadeLineup,
		arg.DemoID,
		arg.Tick,
		arg.MapName,
		arg.GrenadeType,
		arg.ThrowX,
		arg.ThrowY,
		arg.ThrowZ,
		arg.ThrowYaw,
		arg.ThrowPitch,
		arg.LandX,
		arg.LandY,
		arg.LandZ,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.IsFavorite,
	)
	var i GrenadeLineup
	err := row.Scan(
		&i.ID,
		&i.DemoID,
		&i.Tick,
		&i.MapName,
		&i.GrenadeType,
		&i.ThrowX,
		&i.ThrowY,
		&i.ThrowZ,
		&i.ThrowYaw,
		&i.ThrowPitch,
		&i.LandX,
		&i.LandY,
		&i.LandZ,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.IsFavorite,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGrenadeLineup = `-- name: DeleteGrenadeLineup :exec
DELETE FROM grenade_lineups WHERE id = ?1
`

func (q *Queries) DeleteGrenadeLineup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGrenadeLineup, id)
	return err
}

const getGrenadeLineupByID = `-- name: GetGrenadeLineupByID :one
SELECT id, demo_id, tick, map_name, grenade_type, throw_x, throw_y, throw_z, throw_yaw, throw_pitch, land_x, land_y, land_z, title, description, tags, is_favorite, created_at FROM grenade_lineups WHERE id = ?1
`

func (q *Queries) GetGrenadeLineupByID(ctx context.Context, id int64) (GrenadeLineup, error) {
	row := q.db.QueryRowContext(ctx, getGrenadeLineupByID, id)
	var i GrenadeLineup
	err := row.Scan(
		&i.ID,
		&i.DemoID,
		&i.Tick,
		&i.MapName,
		&i.GrenadeType,
		&i.ThrowX,
		&i.ThrowY,
		&i.ThrowZ,
		&i.ThrowYaw,
		&i.ThrowPitch,
		&i.LandX,
		&i.LandY,
		&i.LandZ,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.IsFavorite,
		&i.CreatedAt,
	)
	return i, err
}

const listGrenadeLineups = `-- name: ListGrenadeLineups :many
SELECT id, demo_id, tick, map_name, grenade_type, throw_x, throw_y, throw_z, throw_yaw, throw_pitch, land_x, land_y, land_z, title, description, tags, is_favorite, created_at FROM grenade_lineups
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?1
`

type ListGrenadeLineupsParams struct {
	OffsetVal int64
	LimitVal  int64
}

func (q *Queries) ListGrenadeLineups(ctx context.Context, arg ListGrenadeLineupsParams) ([]GrenadeLineup, error) {
	rows, err := q.db.QueryContext(ctx, listGrenadeLineups, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrenadeLineup
	for rows.Next() {
		var i GrenadeLineup
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.Tick,
			&i.MapName,
			&i.GrenadeType,
			&i.ThrowX,
			&i.ThrowY,
			&i.ThrowZ,
			&i.ThrowYaw,
			&i.ThrowPitch,
			&i.LandX,
			&i.LandY,
			&i.LandZ,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrenadeLineupsByMapAndType = `-- name: ListGrenadeLineupsByMapAndType :many
SELECT id, demo_id, tick, map_name, grenade_type, throw_x, throw_y, throw_z, throw_yaw, throw_pitch, land_x, land_y, land_z, title, description, tags, is_favorite, created_at FROM grenade_lineups
WHERE map_name = ?1 AND grenade_type = ?2
ORDER BY created_at DESC
`

type ListGrenadeLineupsByMapAndTypeParams struct {
	MapName     string
	GrenadeType string
}

func (q *Queries) ListGrenadeLineupsByMapAndType(ctx context.Context, arg ListGrenadeLineupsByMapAndTypeParams) ([]GrenadeLineup, error) {
	rows, err := q.db.QueryContext(ctx, listGrenadeLineupsByMapAndType, arg.MapName, arg.GrenadeType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrenadeLineup
	for rows.Next() {
		var i GrenadeLineup
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.Tick,
			&i.MapName,
			&i.GrenadeType,
			&i.ThrowX,
			&i.ThrowY,
			&i.ThrowZ,
			&i.ThrowYaw,
			&i.ThrowPitch,
			&i.LandX,
			&i.LandY,
			&i.LandZ,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.IsFavorite,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleLineupFavorite = `-- name: ToggleLineupFavorite :one
UPDATE grenade_lineups SET is_favorite = 1 - is_favorite WHERE id = ?1
RETURNING id, demo_id, tick, map_name, grenade_type, throw_x, throw_y, throw_z, throw_yaw, throw_pitch, land_x, land_y, land_z, title, description, tags, is_favorite, created_at
`

func (q *Queries) ToggleLineupFavorite(ctx context.Context, id int64) (GrenadeLineup, error) {
	row := q.db.QueryRowContext(ctx, toggleLineupFavorite, id)
	var i GrenadeLineup
	err := row.Scan(
		&i.ID,
		&i.DemoID,
		&i.Tick,
		&i.MapName,
		&i.GrenadeType,
		&i.ThrowX,
		&i.ThrowY,
		&i.ThrowZ,
		&i.ThrowYaw,
		&i.ThrowPitch,
		&i.LandX,
		&i.LandY,
		&i.LandZ,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.IsFavorite,
		&i.CreatedAt,
	)
	return i, err
}
