// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: heatmaps.sql

package store

import (
	"context"
)

const getDemosByIDs = `-- name: GetDemosByIDs :many
SELECT id, user_id, map_name FROM demos
WHERE id IN (SELECT value FROM json_each(@demo_ids))
`

type GetDemosByIDsRow struct {
	ID      int64
	UserID  int64
	MapName string
}

func (q *Queries) GetDemosByIDs(ctx context.Context) ([]GetDemosByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDemosByIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDemosByIDsRow
	for rows.Next() {
		var i GetDemosByIDsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.MapName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHeatmapAggregation = `-- name: GetHeatmapAggregation :many
SELECT ge.x, ge.y, count(*) AS kill_count
FROM game_events ge
LEFT JOIN player_rounds pr
    ON pr.round_id = ge.round_id AND pr.steam_id = ge.attacker_steam_id
WHERE ge.demo_id IN (SELECT value FROM json_each(@demo_ids))
  AND ge.event_type = 'kill'
  AND ge.x IS NOT NULL
  AND ge.y IS NOT NULL
  AND (?1 IS NULL OR ge.attacker_steam_id = ?1)
  AND (?2 IS NULL OR (pr.team_side IS NOT NULL AND pr.team_side = ?2))
  AND (json_array_length(?3) = 0 OR ge.weapon IN (SELECT value FROM json_each(@weapons)))
GROUP BY ge.x, ge.y
`

type GetHeatmapAggregationParams struct {
	PlayerSteamID interface{}
	Side          interface{}
	Weapons       interface{}
}

type GetHeatmapAggregationRow struct {
	X         float64
	Y         float64
	KillCount int64
}

func (q *Queries) GetHeatmapAggregation(ctx context.Context, arg GetHeatmapAggregationParams) ([]GetHeatmapAggregationRow, error) {
	rows, err := q.db.QueryContext(ctx, getHeatmapAggregation, arg.PlayerSteamID, arg.Side, arg.Weapons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHeatmapAggregationRow
	for rows.Next() {
		var i GetHeatmapAggregationRow
		if err := rows.Scan(&i.X, &i.Y, &i.KillCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
