// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Demo struct {
	ID           int64
	MapName      string
	FilePath     string
	FileSize     int64
	Status       string
	TotalTicks   int64
	TickRate     float64
	DurationSecs int64
	MatchDate    string
	CreatedAt    string
}

type GameEvent struct {
	ID              int64
	DemoID          int64
	RoundID         int64
	Tick            int64
	EventType       string
	AttackerSteamID sql.NullString
	VictimSteamID   sql.NullString
	Weapon          sql.NullString
	X               float64
	Y               float64
	Z               float64
	ExtraData       string
	Headshot        int64
	AssisterSteamID sql.NullString
	HealthDamage    int64
	AttackerName    string
	VictimName      string
	AttackerTeam    string
	VictimTeam      string
}

type GrenadeLineup struct {
	ID          int64
	DemoID      sql.NullInt64
	Tick        int64
	MapName     string
	GrenadeType string
	ThrowX      float64
	ThrowY      float64
	ThrowZ      float64
	ThrowYaw    float64
	ThrowPitch  float64
	LandX       float64
	LandY       float64
	LandZ       float64
	Title       string
	Description string
	Tags        string
	IsFavorite  int64
	CreatedAt   string
}

type PlayerRound struct {
	ID            int64
	RoundID       int64
	SteamID       string
	PlayerName    string
	TeamSide      string
	Kills         int64
	Deaths        int64
	Assists       int64
	Damage        int64
	HeadshotKills int64
	FirstKill     int64
	FirstDeath    int64
	ClutchKills   int64
}

type Round struct {
	ID            int64
	DemoID        int64
	RoundNumber   int64
	StartTick     int64
	EndTick       int64
	WinnerSide    string
	WinReason     string
	CtScore       int64
	TScore        int64
	IsOvertime    int64
	FreezeEndTick int64
	CtTeamName    string
	TTeamName     string
}

type RoundLoadout struct {
	RoundID   int64
	SteamID   string
	Inventory string
}

type StrategyBoard struct {
	ID         int64
	Title      string
	MapName    string
	BoardState string
	CreatedAt  string
	UpdatedAt  string
}

type TickDatum struct {
	DemoID      int64
	Tick        int64
	SteamID     string
	X           float64
	Y           float64
	Z           float64
	Yaw         float64
	Health      int64
	Armor       int64
	IsAlive     int64
	Weapon      string
	Money       int64
	HasHelmet   int64
	HasDefuser  int64
	AmmoClip    int64
	AmmoReserve int64
}
