// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type AnalysisDuel struct {
	ID            int64
	DemoID        int64
	RoundNumber   int64
	RoundID       sql.NullInt64
	AttackerSteam string
	VictimSteam   string
	StartTick     int64
	EndTick       int64
	Outcome       string
	EndReason     string
	HitConfirmed  int64
	HurtCount     int64
	ShotCount     int64
	MutualDuelID  sql.NullInt64
	ExtrasJson    string
	CreatedAt     string
}

type AnalysisMistake struct {
	ID          int64
	DemoID      int64
	SteamID     string
	RoundNumber int64
	Tick        int64
	Kind        string
	ExtrasJson  string
	CreatedAt   string
	Category    string
	Severity    int64
	RoundID     sql.NullInt64
	DuelID      sql.NullInt64
}

type ContactMistake struct {
	ContactID       int64
	Kind            string
	Category        string
	Severity        int64
	Phase           string
	Tick            sql.NullInt64
	ExtrasJson      string
	DetectorVersion int64
}

type ContactMoment struct {
	ID             int64
	DemoID         int64
	RoundID        int64
	SubjectSteam   string
	TFirst         int64
	TLast          int64
	TPre           int64
	TPost          int64
	EnemiesJson    string
	Outcome        string
	SignalCount    int64
	ExtrasJson     string
	BuilderVersion int64
	CreatedAt      string
}

type Demo struct {
	ID           int64
	MapName      string
	FilePath     string
	FileSize     int64
	Status       string
	TotalTicks   int64
	TickRate     float64
	DurationSecs int64
	MatchDate    string
	CreatedAt    string
}

type GameEvent struct {
	ID              int64
	DemoID          int64
	RoundID         int64
	Tick            int64
	EventType       string
	AttackerSteamID sql.NullString
	VictimSteamID   sql.NullString
	Weapon          sql.NullString
	X               float64
	Y               float64
	Z               float64
	ExtraData       string
	Headshot        int64
	AssisterSteamID sql.NullString
	HealthDamage    int64
	AttackerName    string
	VictimName      string
	AttackerTeam    string
	VictimTeam      string
}

type GrenadeLineup struct {
	ID          int64
	DemoID      sql.NullInt64
	Tick        int64
	MapName     string
	GrenadeType string
	ThrowX      float64
	ThrowY      float64
	ThrowZ      float64
	ThrowYaw    float64
	ThrowPitch  float64
	LandX       float64
	LandY       float64
	LandZ       float64
	Title       string
	Description string
	Tags        string
	IsFavorite  int64
	CreatedAt   string
}

type PlayerMatchAnalysis struct {
	ID                         int64
	DemoID                     int64
	SteamID                    string
	OverallScore               int64
	TradePct                   float64
	AvgTradeTicks              float64
	ExtrasJson                 string
	CreatedAt                  string
	Version                    int64
	CrosshairHeightAvgOff      float64
	TimeToFireMsAvg            float64
	FlickCount                 int64
	FlickHitPct                float64
	FirstShotAccPct            float64
	SprayDecaySlope            float64
	StandingShotPct            float64
	CounterStrafePct           float64
	SmokesThrown               int64
	SmokesKillAssist           int64
	FlashAssists               int64
	HeDamage                   int64
	NadesUnused                int64
	IsolatedPeekDeaths         int64
	RepeatedDeathZones         int64
	FullBuyAdr                 float64
	EcoKills                   int64
	TimeToStopMsAvg            float64
	CrouchBeforeShotCount      int64
	CrouchInsteadOfStrafeCount int64
	FlickOvershootAvgDeg       float64
	FlickUndershootAvgDeg      float64
	FlickBalancePct            float64
}

type PlayerRound struct {
	ID            int64
	RoundID       int64
	SteamID       string
	PlayerName    string
	TeamSide      string
	Kills         int64
	Deaths        int64
	Assists       int64
	Damage        int64
	HeadshotKills int64
	FirstKill     int64
	FirstDeath    int64
	ClutchKills   int64
	Survived      int64
	EquipValue    int64
	MoneySpent    int64
	KastRound     int64
}

type PlayerRoundAnalysis struct {
	ID          int64
	DemoID      int64
	SteamID     string
	RoundNumber int64
	TradePct    float64
	ExtrasJson  string
	CreatedAt   string
	BuyType     string
	MoneySpent  int64
	NadesUsed   int64
	NadesUnused int64
	ShotsFired  int64
	ShotsHit    int64
}

type PlayerVisibility struct {
	DemoID       int64
	RoundID      int64
	Tick         int64
	SpottedSteam string
	SpotterSteam string
	State        int64
}

type Round struct {
	ID            int64
	DemoID        int64
	RoundNumber   int64
	StartTick     int64
	EndTick       int64
	WinnerSide    string
	WinReason     string
	CtScore       int64
	TScore        int64
	IsOvertime    int64
	FreezeEndTick int64
	CtTeamName    string
	TTeamName     string
}

type RoundLoadout struct {
	RoundID   int64
	SteamID   string
	Inventory string
}

type StrategyBoard struct {
	ID         int64
	Title      string
	MapName    string
	BoardState string
	CreatedAt  string
	UpdatedAt  string
}

type TickDatum struct {
	DemoID      int64
	Tick        int64
	SteamID     string
	X           float64
	Y           float64
	Z           float64
	Yaw         float64
	Health      int64
	Armor       int64
	IsAlive     int64
	Weapon      string
	Money       int64
	HasHelmet   int64
	HasDefuser  int64
	AmmoClip    int64
	AmmoReserve int64
	Pitch       float64
	Crouch      int64
}
