// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_visibility.sql

package store

import (
	"context"
)

const deleteVisibilityByDemoID = `-- name: DeleteVisibilityByDemoID :exec
DELETE FROM player_visibility WHERE demo_id = ?
`

func (q *Queries) DeleteVisibilityByDemoID(ctx context.Context, demoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteVisibilityByDemoID, demoID)
	return err
}

const insertPlayerVisibility = `-- name: InsertPlayerVisibility :exec
INSERT INTO player_visibility (
    demo_id,
    round_id,
    tick,
    spotted_steam,
    spotter_steam,
    state
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertPlayerVisibilityParams struct {
	DemoID       int64
	RoundID      int64
	Tick         int64
	SpottedSteam string
	SpotterSteam string
	State        int64
}

func (q *Queries) InsertPlayerVisibility(ctx context.Context, arg InsertPlayerVisibilityParams) error {
	_, err := q.db.ExecContext(ctx, insertPlayerVisibility,
		arg.DemoID,
		arg.RoundID,
		arg.Tick,
		arg.SpottedSteam,
		arg.SpotterSteam,
		arg.State,
	)
	return err
}

const listVisibilityForDemo = `-- name: ListVisibilityForDemo :many
SELECT demo_id, round_id, tick, spotted_steam, spotter_steam, state
FROM player_visibility
WHERE demo_id = ?1
ORDER BY round_id ASC, tick ASC, spotted_steam ASC, spotter_steam ASC
`

// Phase 2 contact builder: one demo-scoped fetch, then in-Go partition
// by round_id. Cheaper than round_id-by-round_id queries for the
// per-(player, round) builder loop.
func (q *Queries) ListVisibilityForDemo(ctx context.Context, demoID int64) ([]PlayerVisibility, error) {
	rows, err := q.db.QueryContext(ctx, listVisibilityForDemo, demoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerVisibility
	for rows.Next() {
		var i PlayerVisibility
		if err := rows.Scan(
			&i.DemoID,
			&i.RoundID,
			&i.Tick,
			&i.SpottedSteam,
			&i.SpotterSteam,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibilityForRound = `-- name: ListVisibilityForRound :many
SELECT demo_id, round_id, tick, spotted_steam, spotter_steam, state
FROM player_visibility
WHERE round_id = ?
ORDER BY tick ASC, spotted_steam ASC, spotter_steam ASC
`

func (q *Queries) ListVisibilityForRound(ctx context.Context, roundID int64) ([]PlayerVisibility, error) {
	rows, err := q.db.QueryContext(ctx, listVisibilityForRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerVisibility
	for rows.Next() {
		var i PlayerVisibility
		if err := rows.Scan(
			&i.DemoID,
			&i.RoundID,
			&i.Tick,
			&i.SpottedSteam,
			&i.SpotterSteam,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
