// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_rounds.sql

package store

import (
	"context"
	"database/sql"
)

const createPlayerRound = `-- name: CreatePlayerRound :one
INSERT INTO player_rounds (round_id, steam_id, player_name, team_side, kills, deaths, assists, damage, headshot_kills, first_kill, first_death, clutch_kills)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
RETURNING id, round_id, steam_id, player_name, team_side, kills, deaths, assists, damage, headshot_kills, first_kill, first_death, clutch_kills
`

type CreatePlayerRoundParams struct {
	RoundID       int64
	SteamID       string
	PlayerName    string
	TeamSide      string
	Kills         int64
	Deaths        int64
	Assists       int64
	Damage        int64
	HeadshotKills int64
	FirstKill     int64
	FirstDeath    int64
	ClutchKills   int64
}

func (q *Queries) CreatePlayerRound(ctx context.Context, arg CreatePlayerRoundParams) (PlayerRound, error) {
	row := q.db.QueryRowContext(ctx, createPlayerRound,
		arg.RoundID,
		arg.SteamID,
		arg.PlayerName,
		arg.TeamSide,
		arg.Kills,
		arg.Deaths,
		arg.Assists,
		arg.Damage,
		arg.HeadshotKills,
		arg.FirstKill,
		arg.FirstDeath,
		arg.ClutchKills,
	)
	var i PlayerRound
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.SteamID,
		&i.PlayerName,
		&i.TeamSide,
		&i.Kills,
		&i.Deaths,
		&i.Assists,
		&i.Damage,
		&i.HeadshotKills,
		&i.FirstKill,
		&i.FirstDeath,
		&i.ClutchKills,
	)
	return i, err
}

const deletePlayerRoundsByRoundID = `-- name: DeletePlayerRoundsByRoundID :exec
DELETE FROM player_rounds WHERE round_id = ?1
`

func (q *Queries) DeletePlayerRoundsByRoundID(ctx context.Context, roundID int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayerRoundsByRoundID, roundID)
	return err
}

const getPlayerRoundsByRoundID = `-- name: GetPlayerRoundsByRoundID :many
SELECT id, round_id, steam_id, player_name, team_side, kills, deaths, assists, damage, headshot_kills, first_kill, first_death, clutch_kills FROM player_rounds WHERE round_id = ?1
`

func (q *Queries) GetPlayerRoundsByRoundID(ctx context.Context, roundID int64) ([]PlayerRound, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerRoundsByRoundID, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerRound
	for rows.Next() {
		var i PlayerRound
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.SteamID,
			&i.PlayerName,
			&i.TeamSide,
			&i.Kills,
			&i.Deaths,
			&i.Assists,
			&i.Damage,
			&i.HeadshotKills,
			&i.FirstKill,
			&i.FirstDeath,
			&i.ClutchKills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerRoundsBySteamID = `-- name: GetPlayerRoundsBySteamID :many
SELECT id, round_id, steam_id, player_name, team_side, kills, deaths, assists, damage, headshot_kills, first_kill, first_death, clutch_kills FROM player_rounds WHERE steam_id = ?1
ORDER BY round_id
`

func (q *Queries) GetPlayerRoundsBySteamID(ctx context.Context, steamID string) ([]PlayerRound, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerRoundsBySteamID, steamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerRound
	for rows.Next() {
		var i PlayerRound
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.SteamID,
			&i.PlayerName,
			&i.TeamSide,
			&i.Kills,
			&i.Deaths,
			&i.Assists,
			&i.Damage,
			&i.HeadshotKills,
			&i.FirstKill,
			&i.FirstDeath,
			&i.ClutchKills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerStatsByDemoID = `-- name: GetPlayerStatsByDemoID :many
WITH ranked AS (
    SELECT pr.steam_id, pr.player_name, pr.kills, pr.deaths, pr.assists,
           pr.damage, pr.headshot_kills,
           FIRST_VALUE(pr.team_side) OVER (
               PARTITION BY pr.steam_id ORDER BY r.round_number
           ) AS first_team_side
    FROM player_rounds pr
    JOIN rounds r ON pr.round_id = r.id
    WHERE r.demo_id = ?1
)
SELECT steam_id, player_name,
       CAST(first_team_side AS TEXT) as team_side,
       SUM(kills) as total_kills, SUM(deaths) as total_deaths,
       SUM(assists) as total_assists, SUM(damage) as total_damage,
       SUM(headshot_kills) as total_headshot_kills, COUNT(*) as rounds_played
FROM ranked
GROUP BY steam_id, player_name, first_team_side
ORDER BY team_side, total_kills DESC
`

type GetPlayerStatsByDemoIDRow struct {
	SteamID            string
	PlayerName         string
	TeamSide           string
	TotalKills         sql.NullFloat64
	TotalDeaths        sql.NullFloat64
	TotalAssists       sql.NullFloat64
	TotalDamage        sql.NullFloat64
	TotalHeadshotKills sql.NullFloat64
	RoundsPlayed       int64
}

func (q *Queries) GetPlayerStatsByDemoID(ctx context.Context, demoID int64) ([]GetPlayerStatsByDemoIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerStatsByDemoID, demoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerStatsByDemoIDRow
	for rows.Next() {
		var i GetPlayerStatsByDemoIDRow
		if err := rows.Scan(
			&i.SteamID,
			&i.PlayerName,
			&i.TeamSide,
			&i.TotalKills,
			&i.TotalDeaths,
			&i.TotalAssists,
			&i.TotalDamage,
			&i.TotalHeadshotKills,
			&i.RoundsPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRostersByDemoID = `-- name: GetRostersByDemoID :many
SELECT r.round_number, pr.steam_id, pr.player_name, pr.team_side
FROM player_rounds pr
JOIN rounds r ON pr.round_id = r.id
WHERE r.demo_id = ?1
ORDER BY r.round_number, pr.steam_id
`

type GetRostersByDemoIDRow struct {
	RoundNumber int64
	SteamID     string
	PlayerName  string
	TeamSide    string
}

// Returns one row per (round, player) for the whole demo, ordered by round
// number and steam_id. Used by the viewer to preload every round's roster in
// a single Wails round-trip rather than firing GetRoundRoster on each round
// transition (24-30 trips per match).
func (q *Queries) GetRostersByDemoID(ctx context.Context, demoID int64) ([]GetRostersByDemoIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getRostersByDemoID, demoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRostersByDemoIDRow
	for rows.Next() {
		var i GetRostersByDemoIDRow
		if err := rows.Scan(
			&i.RoundNumber,
			&i.SteamID,
			&i.PlayerName,
			&i.TeamSide,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
