// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_rounds.sql

package store

import (
	"context"
)

const createPlayerRound = `-- name: CreatePlayerRound :one
INSERT INTO player_rounds (round_id, steam_id, player_name, team_side, kills, deaths, assists, damage, headshot_kills, first_kill, first_death, clutch_kills)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
RETURNING id, round_id, steam_id, player_name, team_side, kills, deaths, assists, damage, headshot_kills, first_kill, first_death, clutch_kills
`

type CreatePlayerRoundParams struct {
	RoundID       int64
	SteamID       string
	PlayerName    string
	TeamSide      string
	Kills         int64
	Deaths        int64
	Assists       int64
	Damage        int64
	HeadshotKills int64
	FirstKill     int64
	FirstDeath    int64
	ClutchKills   int64
}

func (q *Queries) CreatePlayerRound(ctx context.Context, arg CreatePlayerRoundParams) (PlayerRound, error) {
	row := q.db.QueryRowContext(ctx, createPlayerRound,
		arg.RoundID,
		arg.SteamID,
		arg.PlayerName,
		arg.TeamSide,
		arg.Kills,
		arg.Deaths,
		arg.Assists,
		arg.Damage,
		arg.HeadshotKills,
		arg.FirstKill,
		arg.FirstDeath,
		arg.ClutchKills,
	)
	var i PlayerRound
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.SteamID,
		&i.PlayerName,
		&i.TeamSide,
		&i.Kills,
		&i.Deaths,
		&i.Assists,
		&i.Damage,
		&i.HeadshotKills,
		&i.FirstKill,
		&i.FirstDeath,
		&i.ClutchKills,
	)
	return i, err
}

const deletePlayerRoundsByRoundID = `-- name: DeletePlayerRoundsByRoundID :exec
DELETE FROM player_rounds WHERE round_id = ?1
`

func (q *Queries) DeletePlayerRoundsByRoundID(ctx context.Context, roundID int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayerRoundsByRoundID, roundID)
	return err
}

const getPlayerRoundsByRoundID = `-- name: GetPlayerRoundsByRoundID :many
SELECT id, round_id, steam_id, player_name, team_side, kills, deaths, assists, damage, headshot_kills, first_kill, first_death, clutch_kills FROM player_rounds WHERE round_id = ?1
`

func (q *Queries) GetPlayerRoundsByRoundID(ctx context.Context, roundID int64) ([]PlayerRound, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerRoundsByRoundID, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerRound
	for rows.Next() {
		var i PlayerRound
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.SteamID,
			&i.PlayerName,
			&i.TeamSide,
			&i.Kills,
			&i.Deaths,
			&i.Assists,
			&i.Damage,
			&i.HeadshotKills,
			&i.FirstKill,
			&i.FirstDeath,
			&i.ClutchKills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerRoundsBySteamID = `-- name: GetPlayerRoundsBySteamID :many
SELECT id, round_id, steam_id, player_name, team_side, kills, deaths, assists, damage, headshot_kills, first_kill, first_death, clutch_kills FROM player_rounds WHERE steam_id = ?1
ORDER BY round_id
`

func (q *Queries) GetPlayerRoundsBySteamID(ctx context.Context, steamID string) ([]PlayerRound, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerRoundsBySteamID, steamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerRound
	for rows.Next() {
		var i PlayerRound
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.SteamID,
			&i.PlayerName,
			&i.TeamSide,
			&i.Kills,
			&i.Deaths,
			&i.Assists,
			&i.Damage,
			&i.HeadshotKills,
			&i.FirstKill,
			&i.FirstDeath,
			&i.ClutchKills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
