// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_match_analysis.sql

package store

import (
	"context"
)

const deletePlayerMatchAnalysisByDemoID = `-- name: DeletePlayerMatchAnalysisByDemoID :exec
DELETE FROM player_match_analysis
WHERE demo_id = ?1
`

func (q *Queries) DeletePlayerMatchAnalysisByDemoID(ctx context.Context, demoID int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayerMatchAnalysisByDemoID, demoID)
	return err
}

const getPlayerMatchAnalysis = `-- name: GetPlayerMatchAnalysis :one
SELECT id, demo_id, steam_id, overall_score, trade_pct, avg_trade_ticks, extras_json, created_at
FROM player_match_analysis
WHERE demo_id = ?1
  AND steam_id = ?2
`

type GetPlayerMatchAnalysisParams struct {
	DemoID  int64
	SteamID string
}

// Returns a single (demo, player) summary row or sql.ErrNoRows if none exists.
func (q *Queries) GetPlayerMatchAnalysis(ctx context.Context, arg GetPlayerMatchAnalysisParams) (PlayerMatchAnalysis, error) {
	row := q.db.QueryRowContext(ctx, getPlayerMatchAnalysis, arg.DemoID, arg.SteamID)
	var i PlayerMatchAnalysis
	err := row.Scan(
		&i.ID,
		&i.DemoID,
		&i.SteamID,
		&i.OverallScore,
		&i.TradePct,
		&i.AvgTradeTicks,
		&i.ExtrasJson,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPlayerMatchAnalysis = `-- name: UpsertPlayerMatchAnalysis :exec
INSERT INTO player_match_analysis (demo_id, steam_id, overall_score, trade_pct, avg_trade_ticks, extras_json)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT(demo_id, steam_id) DO UPDATE SET
    overall_score = excluded.overall_score,
    trade_pct = excluded.trade_pct,
    avg_trade_ticks = excluded.avg_trade_ticks,
    extras_json = excluded.extras_json
`

type UpsertPlayerMatchAnalysisParams struct {
	DemoID        int64
	SteamID       string
	OverallScore  int64
	TradePct      float64
	AvgTradeTicks float64
	ExtrasJson    string
}

// Insert or replace the (demo, player) summary row. The unique index on
// (demo_id, steam_id) gives the ON CONFLICT clause a single target row.
func (q *Queries) UpsertPlayerMatchAnalysis(ctx context.Context, arg UpsertPlayerMatchAnalysisParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayerMatchAnalysis,
		arg.DemoID,
		arg.SteamID,
		arg.OverallScore,
		arg.TradePct,
		arg.AvgTradeTicks,
		arg.ExtrasJson,
	)
	return err
}
