// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_match_analysis.sql

package store

import (
	"context"
)

const countPlayerMatchAnalysisByDemoID = `-- name: CountPlayerMatchAnalysisByDemoID :one
SELECT count(*) FROM player_match_analysis WHERE demo_id = ?1
`

// Returns the number of summary rows persisted for a demo. The slice-5
// analyzer writes one row per rostered player on every successful parse, so
// 0 is the missing-analysis sentinel for legacy demos imported before slice 1.
func (q *Queries) CountPlayerMatchAnalysisByDemoID(ctx context.Context, demoID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayerMatchAnalysisByDemoID, demoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePlayerMatchAnalysisByDemoID = `-- name: DeletePlayerMatchAnalysisByDemoID :exec
DELETE FROM player_match_analysis
WHERE demo_id = ?1
`

func (q *Queries) DeletePlayerMatchAnalysisByDemoID(ctx context.Context, demoID int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayerMatchAnalysisByDemoID, demoID)
	return err
}

const getPlayerMatchAnalysis = `-- name: GetPlayerMatchAnalysis :one
SELECT id, demo_id, steam_id, overall_score, trade_pct, avg_trade_ticks, extras_json, created_at, version, crosshair_height_avg_off, time_to_fire_ms_avg, flick_count, flick_hit_pct, first_shot_acc_pct, spray_decay_slope, standing_shot_pct, counter_strafe_pct, smokes_thrown, smokes_kill_assist, flash_assists, he_damage, nades_unused, isolated_peek_deaths, repeated_death_zones, full_buy_adr, eco_kills, time_to_stop_ms_avg, crouch_before_shot_count, crouch_instead_of_strafe_count, flick_overshoot_avg_deg, flick_undershoot_avg_deg, flick_balance_pct
FROM player_match_analysis
WHERE demo_id = ?1
  AND steam_id = ?2
`

type GetPlayerMatchAnalysisParams struct {
	DemoID  int64
	SteamID string
}

// Returns a single (demo, player) summary row or sql.ErrNoRows if none exists.
func (q *Queries) GetPlayerMatchAnalysis(ctx context.Context, arg GetPlayerMatchAnalysisParams) (PlayerMatchAnalysis, error) {
	row := q.db.QueryRowContext(ctx, getPlayerMatchAnalysis, arg.DemoID, arg.SteamID)
	var i PlayerMatchAnalysis
	err := row.Scan(
		&i.ID,
		&i.DemoID,
		&i.SteamID,
		&i.OverallScore,
		&i.TradePct,
		&i.AvgTradeTicks,
		&i.ExtrasJson,
		&i.CreatedAt,
		&i.Version,
		&i.CrosshairHeightAvgOff,
		&i.TimeToFireMsAvg,
		&i.FlickCount,
		&i.FlickHitPct,
		&i.FirstShotAccPct,
		&i.SprayDecaySlope,
		&i.StandingShotPct,
		&i.CounterStrafePct,
		&i.SmokesThrown,
		&i.SmokesKillAssist,
		&i.FlashAssists,
		&i.HeDamage,
		&i.NadesUnused,
		&i.IsolatedPeekDeaths,
		&i.RepeatedDeathZones,
		&i.FullBuyAdr,
		&i.EcoKills,
		&i.TimeToStopMsAvg,
		&i.CrouchBeforeShotCount,
		&i.CrouchInsteadOfStrafeCount,
		&i.FlickOvershootAvgDeg,
		&i.FlickUndershootAvgDeg,
		&i.FlickBalancePct,
	)
	return i, err
}

const listHabitHistoryForPlayer = `-- name: ListHabitHistoryForPlayer :many
SELECT
    pma.demo_id,
    d.match_date,
    pma.trade_pct,
    pma.time_to_fire_ms_avg,
    pma.first_shot_acc_pct,
    pma.isolated_peek_deaths,
    pma.repeated_death_zones,
    pma.time_to_stop_ms_avg,
    pma.crouch_before_shot_count,
    pma.flick_balance_pct,
    pma.extras_json,
    (SELECT count(*) FROM analysis_mistakes am
     WHERE am.demo_id = pma.demo_id
       AND am.steam_id = pma.steam_id
       AND am.kind = 'no_trade_death') AS untraded_count
FROM player_match_analysis pma
JOIN demos d ON d.id = pma.demo_id
WHERE pma.steam_id = ?1
ORDER BY d.match_date DESC, pma.demo_id DESC
LIMIT ?2
`

type ListHabitHistoryForPlayerParams struct {
	SteamID  string
	LimitVal int64
}

type ListHabitHistoryForPlayerRow struct {
	DemoID                int64
	MatchDate             string
	TradePct              float64
	TimeToFireMsAvg       float64
	FirstShotAccPct       float64
	IsolatedPeekDeaths    int64
	RepeatedDeathZones    int64
	TimeToStopMsAvg       float64
	CrouchBeforeShotCount int64
	FlickBalancePct       float64
	ExtrasJson            string
	UntradedCount         int64
}

// Returns the player's last N analysis rows joined with their demos, ordered
// newest-match-date first. The correlated untraded-deaths count rides along
// so the HabitReport / coaching surfaces can render trend deltas + sparklines
// without a second round trip. Slice 11 chooses on-the-fly aggregation over a
// materialized history table; promote when query latency hurts.
func (q *Queries) ListHabitHistoryForPlayer(ctx context.Context, arg ListHabitHistoryForPlayerParams) ([]ListHabitHistoryForPlayerRow, error) {
	rows, err := q.db.QueryContext(ctx, listHabitHistoryForPlayer, arg.SteamID, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHabitHistoryForPlayerRow
	for rows.Next() {
		var i ListHabitHistoryForPlayerRow
		if err := rows.Scan(
			&i.DemoID,
			&i.MatchDate,
			&i.TradePct,
			&i.TimeToFireMsAvg,
			&i.FirstShotAccPct,
			&i.IsolatedPeekDeaths,
			&i.RepeatedDeathZones,
			&i.TimeToStopMsAvg,
			&i.CrouchBeforeShotCount,
			&i.FlickBalancePct,
			&i.ExtrasJson,
			&i.UntradedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerMatchAnalysisByDemoID = `-- name: ListPlayerMatchAnalysisByDemoID :many
SELECT id, demo_id, steam_id, overall_score, trade_pct, avg_trade_ticks, extras_json, created_at, version, crosshair_height_avg_off, time_to_fire_ms_avg, flick_count, flick_hit_pct, first_shot_acc_pct, spray_decay_slope, standing_shot_pct, counter_strafe_pct, smokes_thrown, smokes_kill_assist, flash_assists, he_damage, nades_unused, isolated_peek_deaths, repeated_death_zones, full_buy_adr, eco_kills, time_to_stop_ms_avg, crouch_before_shot_count, crouch_instead_of_strafe_count, flick_overshoot_avg_deg, flick_undershoot_avg_deg, flick_balance_pct
FROM player_match_analysis
WHERE demo_id = ?1
ORDER BY steam_id ASC
`

// Returns every row persisted for a demo, ordered for stable rendering. Used
// by GetMatchInsights to compute team-level aggregates without N round trips.
func (q *Queries) ListPlayerMatchAnalysisByDemoID(ctx context.Context, demoID int64) ([]PlayerMatchAnalysis, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerMatchAnalysisByDemoID, demoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerMatchAnalysis
	for rows.Next() {
		var i PlayerMatchAnalysis
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.SteamID,
			&i.OverallScore,
			&i.TradePct,
			&i.AvgTradeTicks,
			&i.ExtrasJson,
			&i.CreatedAt,
			&i.Version,
			&i.CrosshairHeightAvgOff,
			&i.TimeToFireMsAvg,
			&i.FlickCount,
			&i.FlickHitPct,
			&i.FirstShotAccPct,
			&i.SprayDecaySlope,
			&i.StandingShotPct,
			&i.CounterStrafePct,
			&i.SmokesThrown,
			&i.SmokesKillAssist,
			&i.FlashAssists,
			&i.HeDamage,
			&i.NadesUnused,
			&i.IsolatedPeekDeaths,
			&i.RepeatedDeathZones,
			&i.FullBuyAdr,
			&i.EcoKills,
			&i.TimeToStopMsAvg,
			&i.CrouchBeforeShotCount,
			&i.CrouchInsteadOfStrafeCount,
			&i.FlickOvershootAvgDeg,
			&i.FlickUndershootAvgDeg,
			&i.FlickBalancePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlayerMatchAnalysis = `-- name: UpsertPlayerMatchAnalysis :exec
INSERT INTO player_match_analysis (
    demo_id, steam_id,
    overall_score, trade_pct, avg_trade_ticks,
    version,
    crosshair_height_avg_off, time_to_fire_ms_avg, flick_count, flick_hit_pct,
    first_shot_acc_pct, spray_decay_slope,
    standing_shot_pct, counter_strafe_pct,
    smokes_thrown, smokes_kill_assist, flash_assists, he_damage, nades_unused,
    isolated_peek_deaths, repeated_death_zones,
    full_buy_adr, eco_kills,
    time_to_stop_ms_avg, crouch_before_shot_count, crouch_instead_of_strafe_count,
    flick_overshoot_avg_deg, flick_undershoot_avg_deg, flick_balance_pct,
    extras_json
) VALUES (
    ?1, ?2,
    ?3, ?4, ?5,
    ?6,
    ?7, ?8, ?9, ?10,
    ?11, ?12,
    ?13, ?14,
    ?15, ?16, ?17, ?18, ?19,
    ?20, ?21,
    ?22, ?23,
    ?24, ?25, ?26,
    ?27, ?28, ?29,
    ?30
)
ON CONFLICT(demo_id, steam_id) DO UPDATE SET
    overall_score                  = excluded.overall_score,
    trade_pct                      = excluded.trade_pct,
    avg_trade_ticks                = excluded.avg_trade_ticks,
    version                        = excluded.version,
    crosshair_height_avg_off       = excluded.crosshair_height_avg_off,
    time_to_fire_ms_avg            = excluded.time_to_fire_ms_avg,
    flick_count                    = excluded.flick_count,
    flick_hit_pct                  = excluded.flick_hit_pct,
    first_shot_acc_pct             = excluded.first_shot_acc_pct,
    spray_decay_slope              = excluded.spray_decay_slope,
    standing_shot_pct              = excluded.standing_shot_pct,
    counter_strafe_pct             = excluded.counter_strafe_pct,
    smokes_thrown                  = excluded.smokes_thrown,
    smokes_kill_assist             = excluded.smokes_kill_assist,
    flash_assists                  = excluded.flash_assists,
    he_damage                      = excluded.he_damage,
    nades_unused                   = excluded.nades_unused,
    isolated_peek_deaths           = excluded.isolated_peek_deaths,
    repeated_death_zones           = excluded.repeated_death_zones,
    full_buy_adr                   = excluded.full_buy_adr,
    eco_kills                      = excluded.eco_kills,
    time_to_stop_ms_avg            = excluded.time_to_stop_ms_avg,
    crouch_before_shot_count       = excluded.crouch_before_shot_count,
    crouch_instead_of_strafe_count = excluded.crouch_instead_of_strafe_count,
    flick_overshoot_avg_deg        = excluded.flick_overshoot_avg_deg,
    flick_undershoot_avg_deg       = excluded.flick_undershoot_avg_deg,
    flick_balance_pct              = excluded.flick_balance_pct,
    extras_json                    = excluded.extras_json
`

type UpsertPlayerMatchAnalysisParams struct {
	DemoID                     int64
	SteamID                    string
	OverallScore               int64
	TradePct                   float64
	AvgTradeTicks              float64
	Version                    int64
	CrosshairHeightAvgOff      float64
	TimeToFireMsAvg            float64
	FlickCount                 int64
	FlickHitPct                float64
	FirstShotAccPct            float64
	SprayDecaySlope            float64
	StandingShotPct            float64
	CounterStrafePct           float64
	SmokesThrown               int64
	SmokesKillAssist           int64
	FlashAssists               int64
	HeDamage                   int64
	NadesUnused                int64
	IsolatedPeekDeaths         int64
	RepeatedDeathZones         int64
	FullBuyAdr                 float64
	EcoKills                   int64
	TimeToStopMsAvg            float64
	CrouchBeforeShotCount      int64
	CrouchInsteadOfStrafeCount int64
	FlickOvershootAvgDeg       float64
	FlickUndershootAvgDeg      float64
	FlickBalancePct            float64
	ExtrasJson                 string
}

// Insert or replace the (demo, player) summary row. The unique index on
// (demo_id, steam_id) gives the ON CONFLICT clause a single target row.
func (q *Queries) UpsertPlayerMatchAnalysis(ctx context.Context, arg UpsertPlayerMatchAnalysisParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayerMatchAnalysis,
		arg.DemoID,
		arg.SteamID,
		arg.OverallScore,
		arg.TradePct,
		arg.AvgTradeTicks,
		arg.Version,
		arg.CrosshairHeightAvgOff,
		arg.TimeToFireMsAvg,
		arg.FlickCount,
		arg.FlickHitPct,
		arg.FirstShotAccPct,
		arg.SprayDecaySlope,
		arg.StandingShotPct,
		arg.CounterStrafePct,
		arg.SmokesThrown,
		arg.SmokesKillAssist,
		arg.FlashAssists,
		arg.HeDamage,
		arg.NadesUnused,
		arg.IsolatedPeekDeaths,
		arg.RepeatedDeathZones,
		arg.FullBuyAdr,
		arg.EcoKills,
		arg.TimeToStopMsAvg,
		arg.CrouchBeforeShotCount,
		arg.CrouchInsteadOfStrafeCount,
		arg.FlickOvershootAvgDeg,
		arg.FlickUndershootAvgDeg,
		arg.FlickBalancePct,
		arg.ExtrasJson,
	)
	return err
}
