// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_round_analysis.sql

package store

import (
	"context"
)

const countPlayerRoundAnalysisByDemoID = `-- name: CountPlayerRoundAnalysisByDemoID :one
SELECT count(*) FROM player_round_analysis WHERE demo_id = ?1
`

// Returns the number of round-level rows persisted for a demo. The slice-7
// analyzer writes one row per (rostered player, round-with-eligible-deaths),
// so 0 is the missing-analysis sentinel for demos imported before slice 7.
func (q *Queries) CountPlayerRoundAnalysisByDemoID(ctx context.Context, demoID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayerRoundAnalysisByDemoID, demoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePlayerRoundAnalysisByDemoID = `-- name: DeletePlayerRoundAnalysisByDemoID :exec
DELETE FROM player_round_analysis
WHERE demo_id = ?1
`

func (q *Queries) DeletePlayerRoundAnalysisByDemoID(ctx context.Context, demoID int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayerRoundAnalysisByDemoID, demoID)
	return err
}

const getPlayerRoundAnalysisByDemoAndPlayer = `-- name: GetPlayerRoundAnalysisByDemoAndPlayer :many
SELECT id, demo_id, steam_id, round_number, trade_pct, extras_json, created_at
FROM player_round_analysis
WHERE demo_id = ?1
  AND steam_id = ?2
ORDER BY round_number ASC
`

type GetPlayerRoundAnalysisByDemoAndPlayerParams struct {
	DemoID  int64
	SteamID string
}

// Returns every (demo, player) round row ordered by round_number ASC so the
// frontend can render the per-round bar chart in match cadence without an
// extra sort.
func (q *Queries) GetPlayerRoundAnalysisByDemoAndPlayer(ctx context.Context, arg GetPlayerRoundAnalysisByDemoAndPlayerParams) ([]PlayerRoundAnalysis, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerRoundAnalysisByDemoAndPlayer, arg.DemoID, arg.SteamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerRoundAnalysis
	for rows.Next() {
		var i PlayerRoundAnalysis
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.SteamID,
			&i.RoundNumber,
			&i.TradePct,
			&i.ExtrasJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlayerRoundAnalysis = `-- name: UpsertPlayerRoundAnalysis :exec
INSERT INTO player_round_analysis (demo_id, steam_id, round_number, trade_pct, extras_json)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(demo_id, steam_id, round_number) DO UPDATE SET
    trade_pct = excluded.trade_pct,
    extras_json = excluded.extras_json
`

type UpsertPlayerRoundAnalysisParams struct {
	DemoID      int64
	SteamID     string
	RoundNumber int64
	TradePct    float64
	ExtrasJson  string
}

// Insert or replace the (demo, player, round) row. The unique index on
// (demo_id, steam_id, round_number) gives the ON CONFLICT clause a single
// target row.
func (q *Queries) UpsertPlayerRoundAnalysis(ctx context.Context, arg UpsertPlayerRoundAnalysisParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayerRoundAnalysis,
		arg.DemoID,
		arg.SteamID,
		arg.RoundNumber,
		arg.TradePct,
		arg.ExtrasJson,
	)
	return err
}
