// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rounds.sql

package store

import (
	"context"
)

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (demo_id, round_number, start_tick, end_tick, winner_side, win_reason, ct_score, t_score)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
RETURNING id, demo_id, round_number, start_tick, end_tick, winner_side, win_reason, ct_score, t_score
`

type CreateRoundParams struct {
	DemoID      int64
	RoundNumber int64
	StartTick   int64
	EndTick     int64
	WinnerSide  string
	WinReason   string
	CtScore     int64
	TScore      int64
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error) {
	row := q.db.QueryRowContext(ctx, createRound,
		arg.DemoID,
		arg.RoundNumber,
		arg.StartTick,
		arg.EndTick,
		arg.WinnerSide,
		arg.WinReason,
		arg.CtScore,
		arg.TScore,
	)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.DemoID,
		&i.RoundNumber,
		&i.StartTick,
		&i.EndTick,
		&i.WinnerSide,
		&i.WinReason,
		&i.CtScore,
		&i.TScore,
	)
	return i, err
}

const deleteRoundsByDemoID = `-- name: DeleteRoundsByDemoID :exec
DELETE FROM rounds WHERE demo_id = ?1
`

func (q *Queries) DeleteRoundsByDemoID(ctx context.Context, demoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRoundsByDemoID, demoID)
	return err
}

const getRoundByDemoAndNumber = `-- name: GetRoundByDemoAndNumber :one
SELECT id, demo_id, round_number, start_tick, end_tick, winner_side, win_reason, ct_score, t_score FROM rounds WHERE demo_id = ?1 AND round_number = ?2
`

type GetRoundByDemoAndNumberParams struct {
	DemoID      int64
	RoundNumber int64
}

func (q *Queries) GetRoundByDemoAndNumber(ctx context.Context, arg GetRoundByDemoAndNumberParams) (Round, error) {
	row := q.db.QueryRowContext(ctx, getRoundByDemoAndNumber, arg.DemoID, arg.RoundNumber)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.DemoID,
		&i.RoundNumber,
		&i.StartTick,
		&i.EndTick,
		&i.WinnerSide,
		&i.WinReason,
		&i.CtScore,
		&i.TScore,
	)
	return i, err
}

const getRoundsByDemoID = `-- name: GetRoundsByDemoID :many
SELECT id, demo_id, round_number, start_tick, end_tick, winner_side, win_reason, ct_score, t_score FROM rounds WHERE demo_id = ?1 ORDER BY round_number
`

func (q *Queries) GetRoundsByDemoID(ctx context.Context, demoID int64) ([]Round, error) {
	rows, err := q.db.QueryContext(ctx, getRoundsByDemoID, demoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Round
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ID,
			&i.DemoID,
			&i.RoundNumber,
			&i.StartTick,
			&i.EndTick,
			&i.WinnerSide,
			&i.WinReason,
			&i.CtScore,
			&i.TScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
