// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: round_loadouts.sql

package store

import (
	"context"
)

const createRoundLoadout = `-- name: CreateRoundLoadout :exec
INSERT INTO round_loadouts (round_id, steam_id, inventory)
VALUES (?1, ?2, ?3)
`

type CreateRoundLoadoutParams struct {
	RoundID   int64
	SteamID   string
	Inventory string
}

func (q *Queries) CreateRoundLoadout(ctx context.Context, arg CreateRoundLoadoutParams) error {
	_, err := q.db.ExecContext(ctx, createRoundLoadout, arg.RoundID, arg.SteamID, arg.Inventory)
	return err
}

const getRoundLoadoutsByDemoID = `-- name: GetRoundLoadoutsByDemoID :many
SELECT r.round_number, rl.steam_id, rl.inventory
FROM round_loadouts rl
JOIN rounds r ON rl.round_id = r.id
WHERE r.demo_id = ?1
ORDER BY r.round_number, rl.steam_id
`

type GetRoundLoadoutsByDemoIDRow struct {
	RoundNumber int64
	SteamID     string
	Inventory   string
}

// Returns every (round_number, steam_id, inventory) triple for a demo so the
// viewer can preload all loadouts in a single Wails round-trip and hand the
// team bars a per-round lookup. ~250 rows total per match.
func (q *Queries) GetRoundLoadoutsByDemoID(ctx context.Context, demoID int64) ([]GetRoundLoadoutsByDemoIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoundLoadoutsByDemoID, demoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoundLoadoutsByDemoIDRow
	for rows.Next() {
		var i GetRoundLoadoutsByDemoIDRow
		if err := rows.Scan(&i.RoundNumber, &i.SteamID, &i.Inventory); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
