// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: strategy_boards.sql

package store

import (
	"context"
)

const createStrategyBoard = `-- name: CreateStrategyBoard :one
INSERT INTO strategy_boards (title, map_name)
VALUES (?1, ?2)
RETURNING id, title, map_name, board_state, created_at, updated_at
`

type CreateStrategyBoardParams struct {
	Title   string
	MapName string
}

func (q *Queries) CreateStrategyBoard(ctx context.Context, arg CreateStrategyBoardParams) (StrategyBoard, error) {
	row := q.db.QueryRowContext(ctx, createStrategyBoard, arg.Title, arg.MapName)
	var i StrategyBoard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.MapName,
		&i.BoardState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStrategyBoard = `-- name: DeleteStrategyBoard :exec
DELETE FROM strategy_boards WHERE id = ?1
`

func (q *Queries) DeleteStrategyBoard(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStrategyBoard, id)
	return err
}

const getStrategyBoardByID = `-- name: GetStrategyBoardByID :one
SELECT id, title, map_name, board_state, created_at, updated_at FROM strategy_boards WHERE id = ?1
`

func (q *Queries) GetStrategyBoardByID(ctx context.Context, id int64) (StrategyBoard, error) {
	row := q.db.QueryRowContext(ctx, getStrategyBoardByID, id)
	var i StrategyBoard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.MapName,
		&i.BoardState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStrategyBoards = `-- name: ListStrategyBoards :many
SELECT id, title, map_name, board_state, created_at, updated_at FROM strategy_boards ORDER BY updated_at DESC
`

func (q *Queries) ListStrategyBoards(ctx context.Context) ([]StrategyBoard, error) {
	rows, err := q.db.QueryContext(ctx, listStrategyBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StrategyBoard
	for rows.Next() {
		var i StrategyBoard
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.MapName,
			&i.BoardState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoardState = `-- name: UpdateBoardState :one
UPDATE strategy_boards SET
    board_state = ?1,
    updated_at = datetime('now')
WHERE id = ?2
RETURNING id, title, map_name, board_state, created_at, updated_at
`

type UpdateBoardStateParams struct {
	BoardState string
	ID         int64
}

func (q *Queries) UpdateBoardState(ctx context.Context, arg UpdateBoardStateParams) (StrategyBoard, error) {
	row := q.db.QueryRowContext(ctx, updateBoardState, arg.BoardState, arg.ID)
	var i StrategyBoard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.MapName,
		&i.BoardState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStrategyBoard = `-- name: UpdateStrategyBoard :one
UPDATE strategy_boards SET
    title = ?1,
    map_name = ?2,
    updated_at = datetime('now')
WHERE id = ?3
RETURNING id, title, map_name, board_state, created_at, updated_at
`

type UpdateStrategyBoardParams struct {
	Title   string
	MapName string
	ID      int64
}

func (q *Queries) UpdateStrategyBoard(ctx context.Context, arg UpdateStrategyBoardParams) (StrategyBoard, error) {
	row := q.db.QueryRowContext(ctx, updateStrategyBoard, arg.Title, arg.MapName, arg.ID)
	var i StrategyBoard
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.MapName,
		&i.BoardState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
