// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tick_data.sql

package store

import (
	"context"
)

const deleteTickDataByDemoID = `-- name: DeleteTickDataByDemoID :exec
DELETE FROM tick_data WHERE demo_id = ?1
`

func (q *Queries) DeleteTickDataByDemoID(ctx context.Context, demoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTickDataByDemoID, demoID)
	return err
}

const getTickDataByRange = `-- name: GetTickDataByRange :many
SELECT demo_id, tick, steam_id, x, y, z, yaw, health, armor, is_alive, weapon FROM tick_data
WHERE demo_id = ?1 AND tick >= ?2 AND tick <= ?3
ORDER BY tick, steam_id
`

type GetTickDataByRangeParams struct {
	DemoID    int64
	StartTick int64
	EndTick   int64
}

func (q *Queries) GetTickDataByRange(ctx context.Context, arg GetTickDataByRangeParams) ([]TickDatum, error) {
	rows, err := q.db.QueryContext(ctx, getTickDataByRange, arg.DemoID, arg.StartTick, arg.EndTick)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TickDatum
	for rows.Next() {
		var i TickDatum
		if err := rows.Scan(
			&i.DemoID,
			&i.Tick,
			&i.SteamID,
			&i.X,
			&i.Y,
			&i.Z,
			&i.Yaw,
			&i.Health,
			&i.Armor,
			&i.IsAlive,
			&i.Weapon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTickDataByRangeAndPlayers = `-- name: GetTickDataByRangeAndPlayers :many
SELECT demo_id, tick, steam_id, x, y, z, yaw, health, armor, is_alive, weapon FROM tick_data
WHERE demo_id = ?1 AND tick >= ?2 AND tick <= ?3
  AND steam_id IN (SELECT value FROM json_each(@steam_ids))
ORDER BY tick, steam_id
`

type GetTickDataByRangeAndPlayersParams struct {
	DemoID    int64
	StartTick int64
	EndTick   int64
}

func (q *Queries) GetTickDataByRangeAndPlayers(ctx context.Context, arg GetTickDataByRangeAndPlayersParams) ([]TickDatum, error) {
	rows, err := q.db.QueryContext(ctx, getTickDataByRangeAndPlayers, arg.DemoID, arg.StartTick, arg.EndTick)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TickDatum
	for rows.Next() {
		var i TickDatum
		if err := rows.Scan(
			&i.DemoID,
			&i.Tick,
			&i.SteamID,
			&i.X,
			&i.Y,
			&i.Z,
			&i.Yaw,
			&i.Health,
			&i.Armor,
			&i.IsAlive,
			&i.Weapon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTickData = `-- name: InsertTickData :exec
INSERT INTO tick_data (demo_id, tick, steam_id, x, y, z, yaw, health, armor, is_alive, weapon)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
`

type InsertTickDataParams struct {
	DemoID  int64
	Tick    int64
	SteamID string
	X       float64
	Y       float64
	Z       float64
	Yaw     float64
	Health  int64
	Armor   int64
	IsAlive int64
	Weapon  string
}

func (q *Queries) InsertTickData(ctx context.Context, arg InsertTickDataParams) error {
	_, err := q.db.ExecContext(ctx, insertTickData,
		arg.DemoID,
		arg.Tick,
		arg.SteamID,
		arg.X,
		arg.Y,
		arg.Z,
		arg.Yaw,
		arg.Health,
		arg.Armor,
		arg.IsAlive,
		arg.Weapon,
	)
	return err
}
