// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CountDemos():Promise<number>;

export function DeleteDemo(arg1:number):Promise<void>;

export function GetAllRosters(arg1:string):Promise<Record<number, Array<main.PlayerRosterEntry>>>;

export function GetDemoByID(arg1:string):Promise<main.Demo>;

export function GetDemoEvents(arg1:string):Promise<Array<main.GameEvent>>;

export function GetDemoRounds(arg1:string):Promise<Array<main.Round>>;

export function GetDemoTicks(arg1:string,arg2:number,arg3:number):Promise<Array<main.TickData>>;

export function GetEventsByTypes(arg1:string,arg2:Array<string>):Promise<Array<main.GameEvent>>;

export function GetHeatmapData(arg1:Array<number>,arg2:Array<string>,arg3:string,arg4:string):Promise<Array<main.HeatmapPoint>>;

export function GetRoundLoadouts(arg1:string):Promise<Record<number, Array<main.RoundLoadoutEntry>>>;

export function GetRoundRoster(arg1:string,arg2:number):Promise<Array<main.PlayerRosterEntry>>;

export function GetScoreboard(arg1:string):Promise<Array<main.ScoreboardEntry>>;

export function GetTolerateEntityErrors():Promise<boolean>;

export function GetUniquePlayers(arg1:Array<number>):Promise<Array<main.PlayerInfo>>;

export function GetUniqueWeapons(arg1:Array<number>):Promise<Array<string>>;

export function GetWeaponStats(arg1:string):Promise<Array<main.WeaponStat>>;

export function Greet(arg1:string):Promise<string>;

export function ImportDemoByPath(arg1:string):Promise<void>;

export function ImportDemoFile():Promise<void>;

export function ListDemos(arg1:number,arg2:number):Promise<main.DemoListResult>;

export function LogsDir():Promise<string>;

export function OpenLogsFolder():Promise<void>;

export function OpenProfilesFolder():Promise<void>;

export function ProfilesDir():Promise<string>;

export function SetTolerateEntityErrors(arg1:boolean):Promise<void>;
