// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDemo(arg1) {
  return window['go']['main']['App']['DeleteDemo'](arg1);
}

export function GetDemoByID(arg1) {
  return window['go']['main']['App']['GetDemoByID'](arg1);
}

export function GetDemoEvents(arg1) {
  return window['go']['main']['App']['GetDemoEvents'](arg1);
}

export function GetDemoRounds(arg1) {
  return window['go']['main']['App']['GetDemoRounds'](arg1);
}

export function GetDemoTicks(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDemoTicks'](arg1, arg2, arg3);
}

export function GetHeatmapData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetHeatmapData'](arg1, arg2, arg3, arg4);
}

export function GetRoundRoster(arg1, arg2) {
  return window['go']['main']['App']['GetRoundRoster'](arg1, arg2);
}

export function GetScoreboard(arg1) {
  return window['go']['main']['App']['GetScoreboard'](arg1);
}

export function GetUniquePlayers(arg1) {
  return window['go']['main']['App']['GetUniquePlayers'](arg1);
}

export function GetUniqueWeapons(arg1) {
  return window['go']['main']['App']['GetUniqueWeapons'](arg1);
}

export function GetWeaponStats(arg1) {
  return window['go']['main']['App']['GetWeaponStats'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportDemoByPath(arg1) {
  return window['go']['main']['App']['ImportDemoByPath'](arg1);
}

export function ImportDemoFile() {
  return window['go']['main']['App']['ImportDemoFile']();
}

export function ImportDemoFolder() {
  return window['go']['main']['App']['ImportDemoFolder']();
}

export function ListDemos(arg1, arg2) {
  return window['go']['main']['App']['ListDemos'](arg1, arg2);
}
