// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountDemos() {
  return window['go']['main']['App']['CountDemos']();
}

export function DeleteDemo(arg1) {
  return window['go']['main']['App']['DeleteDemo'](arg1);
}

export function GetAllRosters(arg1) {
  return window['go']['main']['App']['GetAllRosters'](arg1);
}

export function GetAnalysisStatus(arg1) {
  return window['go']['main']['App']['GetAnalysisStatus'](arg1);
}

export function GetCoachingReport(arg1, arg2) {
  return window['go']['main']['App']['GetCoachingReport'](arg1, arg2);
}

export function GetDemoByID(arg1) {
  return window['go']['main']['App']['GetDemoByID'](arg1);
}

export function GetDemoEvents(arg1) {
  return window['go']['main']['App']['GetDemoEvents'](arg1);
}

export function GetDemoRounds(arg1) {
  return window['go']['main']['App']['GetDemoRounds'](arg1);
}

export function GetDemoTicks(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDemoTicks'](arg1, arg2, arg3);
}

export function GetEventsByTypes(arg1, arg2) {
  return window['go']['main']['App']['GetEventsByTypes'](arg1, arg2);
}

export function GetHabitHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetHabitHistory'](arg1, arg2, arg3);
}

export function GetHabitReport(arg1, arg2) {
  return window['go']['main']['App']['GetHabitReport'](arg1, arg2);
}

export function GetHeatmapData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetHeatmapData'](arg1, arg2, arg3, arg4);
}

export function GetMatchInsights(arg1) {
  return window['go']['main']['App']['GetMatchInsights'](arg1);
}

export function GetMinEngagementsForAimCritique() {
  return window['go']['main']['App']['GetMinEngagementsForAimCritique']();
}

export function GetMistakeContext(arg1) {
  return window['go']['main']['App']['GetMistakeContext'](arg1);
}

export function GetMistakeTimeline(arg1, arg2) {
  return window['go']['main']['App']['GetMistakeTimeline'](arg1, arg2);
}

export function GetNextDrill(arg1, arg2) {
  return window['go']['main']['App']['GetNextDrill'](arg1, arg2);
}

export function GetPlayerAnalysis(arg1, arg2) {
  return window['go']['main']['App']['GetPlayerAnalysis'](arg1, arg2);
}

export function GetPlayerMatchStats(arg1, arg2) {
  return window['go']['main']['App']['GetPlayerMatchStats'](arg1, arg2);
}

export function GetPlayerRoundAnalysis(arg1, arg2) {
  return window['go']['main']['App']['GetPlayerRoundAnalysis'](arg1, arg2);
}

export function GetRoundLoadouts(arg1) {
  return window['go']['main']['App']['GetRoundLoadouts'](arg1);
}

export function GetRoundRoster(arg1, arg2) {
  return window['go']['main']['App']['GetRoundRoster'](arg1, arg2);
}

export function GetScoreboard(arg1) {
  return window['go']['main']['App']['GetScoreboard'](arg1);
}

export function GetTolerateEntityErrors() {
  return window['go']['main']['App']['GetTolerateEntityErrors']();
}

export function GetUniquePlayers(arg1) {
  return window['go']['main']['App']['GetUniquePlayers'](arg1);
}

export function GetUniqueWeapons(arg1) {
  return window['go']['main']['App']['GetUniqueWeapons'](arg1);
}

export function GetWeaponStats(arg1) {
  return window['go']['main']['App']['GetWeaponStats'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportDemoByPath(arg1) {
  return window['go']['main']['App']['ImportDemoByPath'](arg1);
}

export function ImportDemoFile() {
  return window['go']['main']['App']['ImportDemoFile']();
}

export function ListDemos(arg1, arg2) {
  return window['go']['main']['App']['ListDemos'](arg1, arg2);
}

export function LogsDir() {
  return window['go']['main']['App']['LogsDir']();
}

export function OpenLogsFolder() {
  return window['go']['main']['App']['OpenLogsFolder']();
}

export function OpenProfilesFolder() {
  return window['go']['main']['App']['OpenProfilesFolder']();
}

export function ProfilesDir() {
  return window['go']['main']['App']['ProfilesDir']();
}

export function RecomputeAnalysis(arg1) {
  return window['go']['main']['App']['RecomputeAnalysis'](arg1);
}

export function SetMinEngagementsForAimCritique(arg1) {
  return window['go']['main']['App']['SetMinEngagementsForAimCritique'](arg1);
}

export function SetTolerateEntityErrors(arg1) {
  return window['go']['main']['App']['SetTolerateEntityErrors'](arg1);
}
