// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export namespace main {

  export class CurrentStreak {
    type: string;
    count: number;

    static createFrom(source: any = {}): CurrentStreak {
      return new CurrentStreak(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) source = JSON.parse(source);
      this.type = source["type"];
      this.count = source["count"];
    }
  }

  export class PaginationMeta {
    total: number;
    page: number;
    per_page: number;

    static createFrom(source: any = {}): PaginationMeta {
      return new PaginationMeta(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) source = JSON.parse(source);
      this.total = source["total"];
      this.page = source["page"];
      this.per_page = source["per_page"];
    }
  }

  export class Demo {
    id: number;
    map_name: string;
    file_path: string;
    file_size: number;
    status: string;
    total_ticks: number;
    tick_rate: number;
    duration_secs: number;
    match_date: string;
    created_at: string;

    static createFrom(source: any = {}): Demo {
      return new Demo(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) source = JSON.parse(source);
      this.id = source["id"];
      this.map_name = source["map_name"];
      this.file_path = source["file_path"];
      this.file_size = source["file_size"];
      this.status = source["status"];
      this.total_ticks = source["total_ticks"];
      this.tick_rate = source["tick_rate"];
      this.duration_secs = source["duration_secs"];
      this.match_date = source["match_date"];
      this.created_at = source["created_at"];
    }
  }

  export class DemoListResult {
    data: Demo[];
    meta: PaginationMeta;

    static createFrom(source: any = {}): DemoListResult {
      return new DemoListResult(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) source = JSON.parse(source);
      this.data = this.convertValues(source["data"], Demo);
      this.meta = this.convertValues(source["meta"], PaginationMeta);
    }

    convertValues(a: any, classs: any, asMap: boolean = false): any {
      if (!a) { return a; }
      if (a.slice && a.map) { return (a as any[]).map(elem => this.convertValues(elem, classs)); }
      if ("object" === typeof a) {
        if (asMap) {
          for (const key of Object.keys(a)) { a[key] = new classs(a[key]); }
          return a;
        }
        return new classs(a);
      }
      return a;
    }
  }

  export class Round {
    id: string;
    round_number: number;
    start_tick: number;
    end_tick: number;
    winner_side: string;
    win_reason: string;
    ct_score: number;
    t_score: number;
    is_overtime: boolean;

    static createFrom(source: any = {}): Round {
      return new Round(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) source = JSON.parse(source);
      this.id = source["id"];
      this.round_number = source["round_number"];
      this.start_tick = source["start_tick"];
      this.end_tick = source["end_tick"];
      this.winner_side = source["winner_side"];
      this.win_reason = source["win_reason"];
      this.ct_score = source["ct_score"];
      this.t_score = source["t_score"];
      this.is_overtime = source["is_overtime"];
    }
  }

  export class GameEvent {
    id: string;
    demo_id: string;
    round_id: string | null;
    tick: number;
    event_type: string;
    attacker_steam_id: string | null;
    victim_steam_id: string | null;
    weapon: string | null;
    x: number | null;
    y: number | null;
    z: number | null;
    extra_data: Record<string, any> | null;

    static createFrom(source: any = {}): GameEvent {
      return new GameEvent(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) source = JSON.parse(source);
      this.id = source["id"];
      this.demo_id = source["demo_id"];
      this.round_id = source["round_id"];
      this.tick = source["tick"];
      this.event_type = source["event_type"];
      this.attacker_steam_id = source["attacker_steam_id"];
      this.victim_steam_id = source["victim_steam_id"];
      this.weapon = source["weapon"];
      this.x = source["x"];
      this.y = source["y"];
      this.z = source["z"];
      this.extra_data = source["extra_data"];
    }
  }

  export class TickData {
    tick: number;
    steam_id: string;
    x: number;
    y: number;
    z: number;
    yaw: number;
    health: number;
    armor: number;
    is_alive: boolean;
    weapon: string | null;

    static createFrom(source: any = {}): TickData {
      return new TickData(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) source = JSON.parse(source);
      this.tick = source["tick"];
      this.steam_id = source["steam_id"];
      this.x = source["x"];
      this.y = source["y"];
      this.z = source["z"];
      this.yaw = source["yaw"];
      this.health = source["health"];
      this.armor = source["armor"];
      this.is_alive = source["is_alive"];
      this.weapon = source["weapon"];
    }
  }

  export class PlayerRosterEntry {
    steam_id: string;
    player_name: string;
    team_side: string;

    static createFrom(source: any = {}): PlayerRosterEntry {
      return new PlayerRosterEntry(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) source = JSON.parse(source);
      this.steam_id = source["steam_id"];
      this.player_name = source["player_name"];
      this.team_side = source["team_side"];
    }
  }

  export class FaceitProfile {
    nickname: string;
    avatar_url: string | null;
    elo: number | null;
    level: number | null;
    country: string | null;
    matches_played: number;
    current_streak: CurrentStreak;

    static createFrom(source: any = {}): FaceitProfile {
      return new FaceitProfile(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) source = JSON.parse(source);
      this.nickname = source["nickname"];
      this.avatar_url = source["avatar_url"];
      this.elo = source["elo"];
      this.level = source["level"];
      this.country = source["country"];
      this.matches_played = source["matches_played"];
      this.current_streak = this.convertValues(source["current_streak"], CurrentStreak);
    }

    convertValues(a: any, classs: any, asMap: boolean = false): any {
      if (!a) { return a; }
      if ("object" === typeof a) { return new classs(a); }
      return a;
    }
  }

  export class EloHistoryPoint {
    elo: number | null;
    map_name: string;
    played_at: string;

    static createFrom(source: any = {}): EloHistoryPoint {
      return new EloHistoryPoint(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) source = JSON.parse(source);
      this.elo = source["elo"];
      this.map_name = source["map_name"];
      this.played_at = source["played_at"];
    }
  }

  export class FaceitMatch {
    id: string;
    faceit_match_id: string;
    map_name: string;
    score_team: number;
    score_opponent: number;
    result: string;
    elo_before: number | null;
    elo_after: number | null;
    elo_change: number | null;
    kills: number | null;
    deaths: number | null;
    assists: number | null;
    demo_url: string | null;
    demo_id: string | null;
    has_demo: boolean;
    played_at: string;

    static createFrom(source: any = {}): FaceitMatch {
      return new FaceitMatch(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) source = JSON.parse(source);
      this.id = source["id"];
      this.faceit_match_id = source["faceit_match_id"];
      this.map_name = source["map_name"];
      this.score_team = source["score_team"];
      this.score_opponent = source["score_opponent"];
      this.result = source["result"];
      this.elo_before = source["elo_before"];
      this.elo_after = source["elo_after"];
      this.elo_change = source["elo_change"];
      this.kills = source["kills"];
      this.deaths = source["deaths"];
      this.assists = source["assists"];
      this.demo_url = source["demo_url"];
      this.demo_id = source["demo_id"];
      this.has_demo = source["has_demo"];
      this.played_at = source["played_at"];
    }
  }

  export class FaceitMatchListResult {
    data: FaceitMatch[];
    meta: PaginationMeta;

    static createFrom(source: any = {}): FaceitMatchListResult {
      return new FaceitMatchListResult(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) source = JSON.parse(source);
      this.data = this.convertValues(source["data"], FaceitMatch);
      this.meta = this.convertValues(source["meta"], PaginationMeta);
    }

    convertValues(a: any, classs: any, asMap: boolean = false): any {
      if (!a) { return a; }
      if (a.slice && a.map) { return (a as any[]).map(elem => this.convertValues(elem, classs)); }
      if ("object" === typeof a) {
        if (asMap) {
          for (const key of Object.keys(a)) { a[key] = new classs(a[key]); }
          return a;
        }
        return new classs(a);
      }
      return a;
    }
  }

  export class User {
    user_id: string;
    faceit_id: string;
    nickname: string;

    static createFrom(source: any = {}): User {
      return new User(source);
    }

    constructor(source: any = {}) {
      if ('string' === typeof source) source = JSON.parse(source);
      this.user_id = source["user_id"];
      this.faceit_id = source["faceit_id"];
      this.nickname = source["nickname"];
    }
  }

}
